### ISSUE TITLE
Create sample type template

### ISSUE THREAD

**Issue by StuBez** [littlerobot/slims#28]
A sample type template is a collection of attribute types. A later process will store data against each attribute type. This data will apply to all samples of this type.

Each attribute type will have a `label` and a `type`. If an attribute has the type `option`, it *must* have an array of `options` elements.

# Data types
* **name**
  * String
  * 255 characters
  * Required
  * Must be unique in system
* **attributes**, array of:
	* **order**
	  * Integer
	  * Required
	* **label**
	  * String
	  * 255 characters
	  * Required
	  * Must be unique for the sample type template
	* **type**
	  * One of:
	    * brief-text
	    * long-text
	    * option
	    * document
	    * date
	    * colour
	    * user
	* **options** (only for `option` `type`)
	  * Array of strings
	  * 255 characters

# API
## Create
`/api/sample-type-templates [POST]`
```json
{
	"name": "Template name",
	"attributes": [
		{
			"order": 1,
			"label": "Sex",
			"type": "option",
			"options": [
				"Male",
				"Female"
			]
		},
		{
			"order": 2,
			"label": "Age",
			"type": "brief-text"
		},
		{
			"order": 3,
			"label": "Comment",
			"type": "long-text"
		}
	]
}
```

# Mockup
This is just an initial idea - please develop the UI for the best user experience and however works best with ExtJS.
![create sample type template](https://cloud.githubusercontent.com/assets/910068/5633068/b5ff5f6c-95cb-11e4-9883-d09881eef097.png)

# User process
1. User enters sample type template name - this will be used in a later process in a drop-down list.
2. User begins adding attribute types by selecting the type from the drop-down and entering the required information.
3. More attribute types can be added by clicking the "plus" icon.

The option attribute will display two text inputs when it is first selected. It is possible to add more options by clicking the "plus".

**Comment by chuckn0rris** [comment]
![2015-01-07_1217](https://cloud.githubusercontent.com/assets/7203098/5657899/e709da9c-9729-11e4-9e23-6a8f7bd2d5f1.png)

**Comment by chuckn0rris** [comment]
[] Add Templates tab, layout.
[] Templates grid columns, tbar button, actions
[] Attributes grid columns, tbar button, actions
[] 'Add Template' dialog
[] 'Add Attribute' dialog
[] 'Edit attribute' mode for dialog
[] Ajax actions behavior

**Comment by StuBez** [comment]
I've added basic versions of the create (`/api/sample-type-template [POST]`) and get (`/api/sample-type-template [GET]`) endpoints. The JSON request from the issue description should work as expected.

There is no validation and no nice error messages. I also need to write the tests.

Hopefully it will be enough for you to finish your last task. You will need to execute a migration: `php app/console doctrine:migrations:migrate`.

**Comment by StuBez** [comment]
I think this is the process:

# Create template
`/api/sample-type-templates [POST]`
```json
{
    "name": "Template name"
}
```

# Add attribute
`/api/sample-type-templates/[id] [POST]`
```json
{
    "name": "Template name",
    "attributes": [
        {
            "order": 1,
            "label": "Sex",
            "type": "option",
            "options": [
                "Male",
                "Female"
            ]
        }
    ]
}
```

# Add another attribute
`/api/sample-type-templates/[id] [POST]`
```json
{
    "name": "Template name",
    "attributes": [
        {
            "id": 1,
            "order": 1,
            "label": "Sex",
            "type": "option",
            "options": [
                "Male",
                "Female"
            ]
        },
        {
            "order": 2,
            "label": "Age",
            "type": "brief-text"
        }
    ]
}
```

**Comment by StuBez** [comment]
The `GET` API will return a extra field called `editable` for the template. If this is `true`, the template *can* be edited. If it is `false`, the template *can* be edited.

# Example response
```json
{
    "success": true,
    "sample_type_template": {
        "id": 1,
        "name": "Template name",
        "editable": true,
        "attributes": [
            {
                "id": 1,
                "order": 1,
                "label": "Sex",
                "type": "option",
                "options": [
                    "Male",
                    "Female"
                ]
            },
            {
                "id": 2,
                "order": 2,
                "label": "Age",
                "type": "brief-text"
            },
            {
                "id": 3,
                "order": 3,
                "label": "Comment",
                "type": "long-text"
            }
        ]
    }
}
```

**Comment by StuBez** [comment]
@chuckn0rris: I've added the second endpoint so it is now possible to create a template and then add, edit and remove attributes with further requests. Templates can also be renamed.

I don't need the ID of the attributes to be included in the request (a 400 response will be returned if you include them.) The `/api/sample-type-templates/[id] [POST]` needs to be used after the template has been created.

The three request examples work as expected and attributes can be renamed and re-ordered. I have only done a small amount of testing so let me know if you find any bugs.

I've also added the `editable` property to the template. This is always `true` for now but this will change when we develop a future feature. Let me know if you want to add the UI functionality for this now and I'll work out how to make it return `true` or `false` before then.

**Comment by chuckn0rris** [comment]
- [ ] Simple Add attribute, options and not options types
- [ ] Simple Edit attribute
- [ ] Delete attribute
- [ ] Reorder attributes
- [ ] Save selection after add/edit/reorder attributes
- [ ] Validations for attributes
- [ ] Add Editable checking

**Comment by StuBez** [comment]
Two things I noticed when testing:
## Please make attribute type text more friendly.
"Brief text", "Long text", "Document", etc.
![screen shot 2015-01-17 at 15 51 48](https://cloud.githubusercontent.com/assets/910068/5789403/c8463b44-9e60-11e4-9817-e567fdd096b5.png)

## Creating a template with spaces for the name returns a 400 from the API but the UI just displays the spinner and stops responding
![screen shot 2015-01-17 at 15 15 37](https://cloud.githubusercontent.com/assets/910068/5789278/f2997f14-9e5b-11e4-8505-2fda6de0aae7.png)

This seems to happen when there are any validation problems.

**Comment by StuBez** [comment]
I've fixed the problem with the option validation. I still need to add some tests for the API but I think the code is feature complete. I'll close this once the tests are developed.
