### ISSUE TITLE
Store samples

### ISSUE THREAD

**Issue by StuBez** [littlerobot/slims#30]
Storing a sample records the physical samples that are stored in the containers. Each sample will have a [sample type](https://github.com/littlerobot/slims/issues/36) and a [sample instance template](https://github.com/littlerobot/slims/issues/32).

# User process
1. Select a **sample type**. This loads a non-editable table with the label and value for that sample type.
2. Select a **sample instance template**. This loads the form elements so that the user can enter the details for the samples they are storing.
3. Select the container and then positions where the samples will be stored. Multiple positions can be selected, as long as no other samples are already stored there.
4. The user confirms the selected positions and the entered details. This displays an editable table on the right side of the page where they can edit any entered values. This allows them to set values that are different for each sample.
5. The user saves the sample information.

## Notes
* A sample can have a colour associated with it. A colour picker should be added for all sample types. It should be on the left so the same colour can be selected for all samples. It does not have to be added to the right if this is difficult.

# APIs
## Store samples
`/api/samples [POST]`
```json
[
  {
    "container": 5,
    "row": 7,
    "column": 7,
    "colour": null,
    "attributes": [
      {
        "sample_instance_attribute": 12,
        "value": "Los Angeles"
      },
      {
        "sample_instance_attribute": 1,
        "filename": "Manufacturer information.pdf",
        "mime_type": "application/pdf",
        "value": "<base 64 encoded file content>"
      }
    ]
  },
  {
    "container": 5,
    "row": 7,
    "column": 8,
    "colour": "#36f23a",
    "attributes": [
      {
        "sample_instance_attribute": 12,
        "value": "New York"
      },
      {
        "sample_instance_attribute": 1,
        "filename": "Manufacturer information.pdf",
        "mime_type": "application/pdf",
        "value": "<base 64 encoded file content>"
      }
    ]
  },
  {
    ...
  }
]
```

## List sample types
`/api/sample-types [GET]`
```json
{
  "success": true,
  "sample_types": [
    {
      "id": 10,
      "name": "Mouse embryos",
      "sample_type_template_id": 1,
      "attributes": [
        {
          "id": 12,
          "label": "Foo",
          "sample_type_template_attribute_id": 1,
          "value": "Trypsin"
        },
        {
          "id": 13,
          "label": "Bar",
          "sample_type_template_attribute_id": 2,
          "value": "Typice, tam asinos esset mortuis, sicut stupri frixam gallinaceo, sed tu accidere ad detrahendum hoc cacas Dum ego in a transeuntem, tempus sic non wanna te occidere, volo te adjuvet. Sed non hoc tibi, quod mihi non sunt. Praeterea, Ive 'iam fuerunt nimio cacas hoc mane super hoc casu eam tradere vestris mutum asinum."
        },
        {
          "id": 14,
          "label": "Baz",
          "sample_type_template_attribute_id": 3,
          "filename": "spreadsheet.xls",
          "url": "http://www.../spreadsheet.xls"
        },
        {
          "id": 15,
          "label": "FooBar",
          "sample_type_template_attribute_id": 4,
          "value": "2015-02-01",
        }
      ]
    },
    {
      ...
    }
  ]
}
```

## Get sample type
`/api/sample-types/[id] [GET]`
```json
{
  "success": true,
  "sample_type": {
    "id": 10,
    "name": "Mouse embryos",
    "sample_type_template_id": 1,
    "attributes": [
      {
        "id": 12,
        "label": "Foo",
        "sample_type_template_attribute_id": 1,
        "value": "Trypsin"
      },
      {
        "id": 13,
        "label": "Bar",
        "sample_type_template_attribute_id": 2,
        "value": "Typice, tam asinos esset mortuis, sicut stupri frixam gallinaceo, sed tu accidere ad detrahendum hoc cacas Dum ego in a transeuntem, tempus sic non wanna te occidere, volo te adjuvet. Sed non hoc tibi, quod mihi non sunt. Praeterea, Ive 'iam fuerunt nimio cacas hoc mane super hoc casu eam tradere vestris mutum asinum."
      },
      {
        "id": 14,
        "label": "Baz",
        "sample_type_template_attribute_id": 3,
        "filename": "spreadsheet.xls",
        "url": "http://www.../spreadsheet.xls"
      },
      {
        "id": 15,
        "label": "FooBar",
        "sample_type_template_attribute_id": 4,
        "value": "2015-02-01",
      }
    ]
  }
}
```

## List sample instances
`/api/sample-instance-template [GET]`
```json
{
  "success": true,
  "sample_instance_templates": [
    {
      "name": "Template name",
      "attributes": {
        "store": [
          {
            "order": 1,
            "label": "Sex",
            "type": "option",
            "options": [
              "Male",
              "Female"
            ]
          },
          {
            "order": 2,
            "label": "Age",
            "type": "brief-text"
          },
          {
            "order": 3,
            "label": "Comment",
            "type": "long-text"
          },
          {
            "order": 4,
            "label": "Stored by",
            "type": "user"
          },
          {
            "order": 5,
            "label": "Date stored",
            "type": "date"
          }
        ]
      },
      "remove": [
        {
          "order": 1,
          "label": "Reason",
          "type": "long-text"
        },
        {
          "order": 2,
          "label": "Removed by",
          "type": "user"
        },
        {
          "order": 3,
          "label": "Date removed",
          "type": "date"
        }
      ]
    },
    {
      ...
    }
  ]
}
```

## Get sample instance
*To be developed*

## List containers
`/api/containers [GET]`
```json
{
  "success": true,
  "data": [
    {
      "leaf": false,
      "sample_remaining_capacity": 1429,
      "sample_total_capacity": 1429,
      "samples_stored": 0,
      "id": 1,
      "name": "Aut aut.",
      "research_group": {
        "id": 25,
        "name": "Research group AAA"
      },
      "rows": 1,
      "columns": 10,
      "stores": "containers",
      "comment": "Molestiae voluptatem totam aut quae.",
      "data": [
        {
          "leaf": false,
          "sample_remaining_capacity": 391,
          "sample_total_capacity": 391,
          "samples_stored": 0,
          "id": 7,
          "name": "Sed dolorem.",
          "research_group": {
            "id": 28,
            "name": "Research group D"
          },
          "rows": 8,
          "columns": 3,
          "stores": "containers",
          "comment": "Enim officia et sit aut voluptates et.",
          "colour": "#c331b6"
        }
      ]
    }
  ]
}
```
*Needs further development*

> Can the current sample positions be included in the containers API response or should it be separate to reduce the amount of data? It will need to include at least a row, a column and a colour.

# Mockup
![store samples](https://cloud.githubusercontent.com/assets/910068/5892351/c88ba48c-a4b3-11e4-904c-6607f925d32d.png)

**Comment by chuckn0rris** [comment]
@StuBez 
We need to rename 
`sample_type_template_id` -> `sample_type_template`
`sample_type_template_attribute_id` -> `sample_type_template_attribute`

Also I not see `positions list` action, `set sample` action

**Comment by StuBez** [comment]
I will make sure the APIs have the renamed elements.

I think the positions could be in the container list API? That API could also list all the samples that are in the container?

Is "set sample" the same as `/api/samples [POST]`? Samples cannot be updated once they have been saved - they can only be stored and removed.

**Comment by chuckn0rris** [comment]
May be you are right about positions in containers list. But if we will add positions list and samples list on each positions - it will be very much information. 
What if we will have separated methods - 
`containerslist` - list of containers with positionId.
`positonslist/{containerId}` - list of busy positions with some info about stored samples

/api/samples [POST] - Yes, it is what I mean. Sorry, I was confused - sampleS and array as response (request), and I thought it is just samples list...

**Comment by StuBez** [comment]
I agree that it will be a lot of information so it may not be a good idea. I will think about this for the next few days.

**Comment by chuckn0rris** [comment]
- [ ] Tab mockup
- [ ] Forms for selection process
- [ ] Positions grid component
- [ ] AJAX

**Comment by chuckn0rris** [comment]
@StuBez What do you think if I'll try do grouping of our tabs into subtabs according to usage? And our main tab menu will be little bit more clear. I think I will have good ideas but if you feel ok for that.

**Comment by chuckn0rris** [comment]
Something like this...
![slims_tabs_align](https://cloud.githubusercontent.com/assets/7203098/7004155/f77fef86-dc90-11e4-807e-c082dcbf5e09.png)

**Comment by StuBez** [comment]
I like that - there were too many tabs at the top before but that makes it much better. :+1:

**Comment by StuBez** [comment]
If you start committing any code, please can you create a branch called `feature/30-store-samples`. Thank you.

**Comment by chuckn0rris** [comment]
OK

**Comment by StuBez** [comment]
What do you think of these ideas for information about positions and the samples that are stored in them?

1. An `/api/containers/[id]/samples` API that lists the positions that have samples and details of the sample in each position. The key will be the row and column position. E.g. `10:25` would be row 10, column 25.

  ```json
  ...
  "10:25": {
    "id": 100,
    "sample_data": "fsgdsfsdgs",
    "more_sample_data": "fdsfdsgsrgw"
  },
  "10:26": {
    "id": 101,
    ...
  },
  ...
```
2. The same as 1., but even empty positions have an entry:

  ```json
  ...
  "10:26": {
    "id": 101,
    ...
  },
  "10:27": null,
  "10:28": null
  ...
  ```

**Comment by chuckn0rris** [comment]
how about to create a two-dimensional array?
12 Апр 2015 г. 22:24 пользователь "Stuart Chapman" <notifications@github.com>
написал:

**Comment by StuBez** [comment]
I did wonder about that but thought it might be a bit more complicated. As you are consuming the API, I'm happy with whatever is easiest for you.

Would the first dimension of the array be the row and then each position in the column?

**Comment by chuckn0rris** [comment]
It doesn't matter here. You can implement it as you comfortable, because it
will be easy to parse for me in any case.
12 Апр 2015 г. 22:52 пользователь "Stuart Chapman" <notifications@github.com>
написал:

**Comment by StuBez** [comment]
There are now first versions of the get samples (`/api/container/[id]/samples [GET]`) and store samples (`/api/container/[id]/samples [POST]`) APIs.

The `GET` API includes too much information and the structure and information is probably not exactly what you need. I think it could also be simplified for the relations between the templates and the actual stored values.

The `POST` API is definitely incomplete but is hopefully enough to get started with.

# Examples
```json
{
    "row": 1,
    "column": 4,
    "type": 5,
    "template": 7,
    "attributes": [
        {
            "id": 1,
            "value": "Male"
        }
    ]
}
```

```json
{
    "success": true,
    "samples": {
        "1:1": {
            "type": {
                "sample_type_template": 1,
                "id": 1,
                "name": "Test sample type",
                "attributes": [
                    {
                        "sample_type_template": 1,
                        "label": "Sex",
                        "id": 1,
                        "value": "Trypsin"
                    },
                    {
                        "sample_type_template": 2,
                        "label": "Age",
                        "id": 2,
                        "value": "Typice, tam asinos esset mortuis, sicut stupri frixam gallinaceo, sed tu accidere ad detrahendum hoc cacas Dum ego in a transeuntem, tempus sic non wanna te occidere, volo te adjuvet. Sed non hoc tibi, quod mihi non sunt. Praeterea, Ive 'iam fuerunt nimio cacas hoc mane super hoc casu eam tradere vestris mutum asinum."
                    },
                    {
                        "sample_type_template": 3,
                        "label": "Comment",
                        "id": 3,
                        "filename": "spreadsheet.xls",
                        "mime_type": "application/vnd.ms-excel",
                        "url": "/app_dev.php/download/3/spreadsheet.xls"
                    },
                    {
                        "sample_type_template": 4,
                        "label": "Date",
                        "id": 4,
                        "value": "2015-02-02"
                    }
                ]
            },
            "template": {
                "id": 8,
                "name": "Template name 3",
                "store": [
                    {
                        "id": 4,
                        "order": 1,
                        "label": "Store Sex",
                        "type": "option",
                        "options": [
                            "Male",
                            "Female"
                        ],
                        "activity": "store"
                    },
                    {
                        "id": 5,
                        "order": 2,
                        "label": "Store Age",
                        "type": "brief-text",
                        "activity": "store"
                    },
                    {
                        "id": 6,
                        "order": 3,
                        "label": "Store Comment",
                        "type": "long-text",
                        "activity": "store"
                    }
                ],
                "remove": [
                    {
                        "id": 7,
                        "order": 1,
                        "label": "Remove Sex",
                        "type": "option",
                        "options": [
                            "Male",
                            "Female"
                        ],
                        "activity": "remove"
                    },
                    {
                        "id": 8,
                        "order": 2,
                        "label": "Remove Age",
                        "type": "brief-text",
                        "activity": "remove"
                    },
                    {
                        "id": 9,
                        "order": 3,
                        "label": "Remove Comment",
                        "type": "long-text",
                        "activity": "remove"
                    }
                ]
            },
            "attributes": [
                {
                    "id": 1,
                    "value": "Male"
                }
            ]
        },
        "1:2": {
            "type": {
                "sample_type_template": 1,
                "id": 4,
                "name": "Mouse embryos",
                "attributes": [
                    {
                        "sample_type_template": 1,
                        "label": "Sex",
                        "id": 9,
                        "value": "Trypsin"
                    },
                    {
                        "sample_type_template": 2,
                        "label": "Age",
                        "id": 10,
                        "value": "Typice, tam asinos esset mortuis, sicut stupri frixam gallinaceo, sed tu accidere ad detrahendum hoc cacas Dum ego in a transeuntem, tempus sic non wanna te occidere, volo te adjuvet. Sed non hoc tibi, quod mihi non sunt. Praeterea, Ive 'iam fuerunt nimio cacas hoc mane super hoc casu eam tradere vestris mutum asinum."
                    },
                    {
                        "sample_type_template": 3,
                        "label": "Comment",
                        "id": 11,
                        "filename": "spreadsheet.xls",
                        "mime_type": "application/vnd.ms-excel",
                        "url": "/app_dev.php/download/11/spreadsheet.xls"
                    },
                    {
                        "sample_type_template": 4,
                        "label": "Date",
                        "id": 12,
                        "value": "2015-02-01"
                    }
                ]
            },
            "template": {
                "id": 8,
                "name": "Template name 3",
                "store": [
                    {
                        "id": 4,
                        "order": 1,
                        "label": "Store Sex",
                        "type": "option",
                        "options": [
                            "Male",
                            "Female"
                        ],
                        "activity": "store"
                    },
                    {
                        "id": 5,
                        "order": 2,
                        "label": "Store Age",
                        "type": "brief-text",
                        "activity": "store"
                    },
                    {
                        "id": 6,
                        "order": 3,
                        "label": "Store Comment",
                        "type": "long-text",
                        "activity": "store"
                    }
                ],
                "remove": [
                    {
                        "id": 7,
                        "order": 1,
                        "label": "Remove Sex",
                        "type": "option",
                        "options": [
                            "Male",
                            "Female"
                        ],
                        "activity": "remove"
                    },
                    {
                        "id": 8,
                        "order": 2,
                        "label": "Remove Age",
                        "type": "brief-text",
                        "activity": "remove"
                    },
                    {
                        "id": 9,
                        "order": 3,
                        "label": "Remove Comment",
                        "type": "long-text",
                        "activity": "remove"
                    }
                ]
            },
            "attributes": []
        },
        "1:3": {
            "type": {
                "sample_type_template": 1,
                "id": 4,
                "name": "Mouse embryos",
                "attributes": [
                    {
                        "sample_type_template": 1,
                        "label": "Sex",
                        "id": 9,
                        "value": "Trypsin"
                    },
                    {
                        "sample_type_template": 2,
                        "label": "Age",
                        "id": 10,
                        "value": "Typice, tam asinos esset mortuis, sicut stupri frixam gallinaceo, sed tu accidere ad detrahendum hoc cacas Dum ego in a transeuntem, tempus sic non wanna te occidere, volo te adjuvet. Sed non hoc tibi, quod mihi non sunt. Praeterea, Ive 'iam fuerunt nimio cacas hoc mane super hoc casu eam tradere vestris mutum asinum."
                    },
                    {
                        "sample_type_template": 3,
                        "label": "Comment",
                        "id": 11,
                        "filename": "spreadsheet.xls",
                        "mime_type": "application/vnd.ms-excel",
                        "url": "/app_dev.php/download/11/spreadsheet.xls"
                    },
                    {
                        "sample_type_template": 4,
                        "label": "Date",
                        "id": 12,
                        "value": "2015-02-01"
                    }
                ]
            },
            "template": {
                "id": 8,
                "name": "Template name 3",
                "store": [
                    {
                        "id": 4,
                        "order": 1,
                        "label": "Store Sex",
                        "type": "option",
                        "options": [
                            "Male",
                            "Female"
                        ],
                        "activity": "store"
                    },
                    {
                        "id": 5,
                        "order": 2,
                        "label": "Store Age",
                        "type": "brief-text",
                        "activity": "store"
                    },
                    {
                        "id": 6,
                        "order": 3,
                        "label": "Store Comment",
                        "type": "long-text",
                        "activity": "store"
                    }
                ],
                "remove": [
                    {
                        "id": 7,
                        "order": 1,
                        "label": "Remove Sex",
                        "type": "option",
                        "options": [
                            "Male",
                            "Female"
                        ],
                        "activity": "remove"
                    },
                    {
                        "id": 8,
                        "order": 2,
                        "label": "Remove Age",
                        "type": "brief-text",
                        "activity": "remove"
                    },
                    {
                        "id": 9,
                        "order": 3,
                        "label": "Remove Comment",
                        "type": "long-text",
                        "activity": "remove"
                    }
                ]
            },
            "attributes": []
        },
        "1:4": {
            "type": {
                "sample_type_template": 1,
                "id": 5,
                "name": "Mouse embryos2",
                "attributes": [
                    {
                        "sample_type_template": 1,
                        "label": "Sex",
                        "id": 13,
                        "value": "Trypsin"
                    },
                    {
                        "sample_type_template": 2,
                        "label": "Age",
                        "id": 14,
                        "value": "Typice, tam asinos esset mortuis, sicut stupri frixam gallinaceo, sed tu accidere ad detrahendum hoc cacas Dum ego in a transeuntem, tempus sic non wanna te occidere, volo te adjuvet. Sed non hoc tibi, quod mihi non sunt. Praeterea, Ive 'iam fuerunt nimio cacas hoc mane super hoc casu eam tradere vestris mutum asinum."
                    },
                    {
                        "sample_type_template": 3,
                        "label": "Comment",
                        "id": 15,
                        "filename": "spreadsheet.xls",
                        "mime_type": "application/vnd.ms-excel",
                        "url": "/app_dev.php/download/15/spreadsheet.xls"
                    },
                    {
                        "sample_type_template": 4,
                        "label": "Date",
                        "id": 16,
                        "value": "2015-02-01"
                    }
                ]
            },
            "template": {
                "id": 7,
                "name": "Template name",
                "store": [
                    {
                        "id": 1,
                        "order": 1,
                        "label": "Store Sex",
                        "type": "option",
                        "options": [
                            "Male",
                            "Female"
                        ],
                        "activity": "store"
                    },
                    {
                        "id": 2,
                        "order": 2,
                        "label": "Store Age",
                        "type": "brief-text",
                        "activity": "store"
                    },
                    {
                        "id": 3,
                        "order": 3,
                        "label": "Store Comment",
                        "type": "long-text",
                        "activity": "store"
                    }
                ],
                "remove": []
            },
            "attributes": [
                {
                    "id": 4,
                    "value": "Male"
                }
            ]
        }
    }
}
```

Let me know what your ideas are and I'll make those changes.

**Comment by chuckn0rris** [comment]
I think we should add `sizes` of positions container

**Comment by StuBez** [comment]
Could you add full examples of the API requests and responses you want and
I'll make those changes?

On Saturday, 2 May 2015, chuckn0rris <notifications@github.com> wrote:

> I think we should add sizes of positions container
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/littlerobot/slims/issues/30#issuecomment-98325949>.
>

-- 


little robot Limited is a company registered in England and Wales. 
Registered number: 8923395. Registered office: CPC1, Capital Park, 
Fulbourn, Cambridgeshire, CB21 5XE.

**Comment by chuckn0rris** [comment]
`/app_dev.php/api/container/13/samples` returns 404
migration returns error
![migration_error](https://cloud.githubusercontent.com/assets/7203098/7441104/c38c2970-f102-11e4-9079-c03f73390262.png)

**Comment by chuckn0rris** [comment]
@StuBez 
Positions view looks now:
![positions_view](https://cloud.githubusercontent.com/assets/7203098/7548790/d6be03ba-f643-11e4-898e-28b66210633a.png)

**Comment by chuckn0rris** [comment]
@StuBez About container's samples list [GET]

```json
return {
            "success": true,
            "samples": {
                "1:1": {
                    "type": {
                        "sample_type_template": 1,
                        "sample_type_template_name": "Template 1",
                        "id": 1,
                        "name": "Test sample type"
                    },
                    "template": {
                        "id": 8,
                        "name": "Template name 3"
                    },
                    "attributes": [
                        {
                            "id": 1,
                            "value": "Male"
                        }
                    ],
                    "color": "blue"
                },
                "1:2": {
                    "type": {
                        "sample_type_template": 1,
                        "sample_type_template_name": "Template 1",
                        "id": 4,
                        "name": "Mouse embryos"
                    },
                    "template": {
                        "id": 8,
                        "name": "Template name 3"
                    },
                    "attributes": [],
                    "color": "red"
                }
        }
}
```

I think this is more than enougth for this view, because we only need to show info here.
Сorrect me if I forgot something.

**Comment by chuckn0rris** [comment]
I still have an error 404 on `/api/container/25/samples` [GET] and all other ids

**Comment by chuckn0rris** [comment]
I changed style for subtabs buttons.
![new_tabs_buttons_style](https://cloud.githubusercontent.com/assets/7203098/7549255/1af120ee-f658-11e4-92fd-85b8a370c15b.png)

**Comment by chuckn0rris** [comment]
Cannot create sample type, 400 error. I trying to create sample type with `brief text` fields, but error occured 
I sent [POST] `api/sample-types`
```javascript
{
  "name": "3443554",
  "sample_type_template": 2,
  "attributes": [
    {
      "id": 3,
      "value": "3454354"
    },
    {
      "id": 4,
      "value": "werwe"
    },
    {
      "id": 5,
      "value": "werewre"
    }
  ]
}
```
server response
```javascript
{
  "code": 400,
  "message": "Validation Failed",
  "errors": {
    "errors": [
      "This form should not contain extra fields.",
      "This form should not contain extra fields.",
      "This form should not contain extra fields."
    ],
    "children": {
      "name": [
        
      ],
      "sample_type_template": [
        
      ],
      "attributes": {
        "children": [
          {
            "children": {
              "template": [
                
              ],
              "value": [
                
              ],
              "mime_type": [
                
              ],
              "filename": {
                "errors": [
                  "A document must have a filename."
                ]
              }
            }
          },
          {
            "children": {
              "template": [
                
              ],
              "value": [
                
              ],
              "mime_type": [
                
              ],
              "filename": {
                "errors": [
                  "A document must have a filename."
                ]
              }
            }
          },
          {
            "children": {
              "template": [
                
              ],
              "value": [
                
              ],
              "mime_type": [
                
              ],
              "filename": {
                "errors": [
                  "A document must have a filename."
                ]
              }
            }
          }
        ]
      }
    }
  }
}
```

Sample type teplate looks like
![type_template](https://cloud.githubusercontent.com/assets/7203098/7549403/14d81672-f65d-11e4-9185-fd3ceb6aba8f.png)

**Comment by StuBez** [comment]
All the new designs look great. I sent the previous designs for feedback
but I think they will like the new ones even better.

I will look into the API issues in a week. Is that all you need for this
feature to be complete? There is a bug I added recently if you have time.

On Saturday, May 9, 2015, chuckn0rris <notifications@github.com> wrote:

> Cannot create sample type, 400 error. I trying to create sample type with brief
> text fields, but error occured
> I sent [POST] api/sample-types
>
> {
>   "name": "3443554",
>   "sample_type_template": 2,
>   "attributes": [
>     {
>       "id": 3,
>       "value": "3454354"
>     },
>     {
>       "id": 4,
>       "value": "werwe"
>     },
>     {
>       "id": 5,
>       "value": "werewre"
>     }
>   ]
> }
>
> server response
>
> {
>   "code": 400,
>   "message": "Validation Failed",
>   "errors": {
>     "errors": [
>       "This form should not contain extra fields.",
>       "This form should not contain extra fields.",
>       "This form should not contain extra fields."
>     ],
>     "children": {
>       "name": [
>
>       ],
>       "sample_type_template": [
>
>       ],
>       "attributes": {
>         "children": [
>           {
>             "children": {
>               "template": [
>
>               ],
>               "value": [
>
>               ],
>               "mime_type": [
>
>               ],
>               "filename": {
>                 "errors": [
>                   "A document must have a filename."
>                 ]
>               }
>             }
>           },
>           {
>             "children": {
>               "template": [
>
>               ],
>               "value": [
>
>               ],
>               "mime_type": [
>
>               ],
>               "filename": {
>                 "errors": [
>                   "A document must have a filename."
>                 ]
>               }
>             }
>           },
>           {
>             "children": {
>               "template": [
>
>               ],
>               "value": [
>
>               ],
>               "mime_type": [
>
>               ],
>               "filename": {
>                 "errors": [
>                   "A document must have a filename."
>                 ]
>               }
>             }
>           }
>         ]
>       }
>     }
>   }
> }
>
> Sample type teplate looks like
> [image: type_template]
> <https://cloud.githubusercontent.com/assets/7203098/7549403/14d81672-f65d-11e4-9185-fd3ceb6aba8f.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/littlerobot/slims/issues/30#issuecomment-100445654>.
>

-- 


little robot Limited is a company registered in England and Wales. 
Registered number: 8923395. Registered office: CPC1, Capital Park, 
Fulbourn, Cambridgeshire, CB21 5XE.

**Comment by chuckn0rris** [comment]
I already fixed those bug.
9 Май 2015 г. 15:39 пользователь "Stuart Chapman" <notifications@github.com>
написал:

> All the new designs look great. I sent the previous designs for feedback
> but I think they will like the new ones even better.
>
> I will look into the API issues in a week. Is that all you need for this
> feature to be complete? There is a bug I added recently if you have time.
>

**Comment by chuckn0rris** [comment]
I am sorry, error code there **400** now

**Comment by chuckn0rris** [comment]
@StuBez  Do not worry about my comments! I just leave it here and you can give answers when you back from holydays!

**Comment by StuBez** [comment]
The get samples API now returns the following response:
```json
{
  "success": true,
  "samples": {
    "1:1": {
      "colour": "#0044fd",
      "type": {
        "sample_type_template": 1,
        "sample_type_template_name": "Template name",
        "id": 1,
        "name": "Test sample type"
      },
      "template": {
        "id": 8,
        "name": "Template name 3"
      },
      "attributes": [
        {
          "id": 1,
          "value": "Male"
        }
      ]
    },
    "1:2": {
      "type": {
        "sample_type_template": 1,
        "sample_type_template_name": "Template name",
        "id": 4,
        "name": "Mouse embryos"
      },
      "template": {
        "id": 8,
        "name": "Template name 3"
      },
      "attributes": []
    },
    "1:3": {
      "type": {
        "sample_type_template": 1,
        "sample_type_template_name": "Template name",
        "id": 4,
        "name": "Mouse embryos"
      },
      "template": {
        "id": 8,
        "name": "Template name 3"
      },
      "attributes": []
    },
    "1:4": {
      "type": {
        "sample_type_template": 1,
        "sample_type_template_name": "Template name",
        "id": 5,
        "name": "Mouse embryos2"
      },
      "template": {
        "id": 7,
        "name": "Template name"
      },
      "attributes": [
        {
          "id": 4,
          "value": "Male"
        }
      ]
    }
  }
}
```
I think it now has all the fields you specified.

**Comment by StuBez** [comment]
The problem storing sample types (https://github.com/littlerobot/slims/issues/30#issuecomment-100445654) is now fixed.

**Comment by StuBez** [comment]
I think the `404` problem is because you need to add an 's' so that it is 'container**s**'. Try `/api/containers/{id}/samples`.

**Comment by StuBez** [comment]
@chuckn0rris: I still need to add some tests and validation for the API but I think the problems you had are now fixed. Please let me know if you still have problems.

**Comment by chuckn0rris** [comment]
@StuBez 
I am looking at `POST api\samples ` at the description
Why we should use an array there?
What if I will send smthng like this
```
{
  sample_template_id: 10,
  sample_instance_template_id: 2,
  container_id: 22,
  store_attributes: {
        attribute1: value1,
        attribute2: value2
    },
  posiitons: ["2:2", "3:10", "3:11", "3:12"],
  colour: "#3300AA"
}
```

**Comment by chuckn0rris** [comment]
@StuBez Does `GET api\samples` ready now? I got 404 error

**Comment by StuBez** [comment]
The URL to get the samples in a container is
/api/containers/{container id}/samples

On Sunday, 31 May 2015, chuckn0rris <notifications@github.com> wrote:

> @StuBez <https://github.com/StuBez> Does GET api\samples ready now? I got
> 404 error
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/littlerobot/slims/issues/30#issuecomment-107133063>.
>

-- 


little robot Limited is a company registered in England and Wales. 
Registered number: 8923395. Registered office: CPC1, Capital Park, 
Fulbourn, Cambridgeshire, CB21 5XE.

**Comment by StuBez** [comment]
I don't completely understand your questions.

The positions can't be an array like that because the information stored
for each sample will normally be a little bit different for each one.

On Sunday, 31 May 2015, chuckn0rris <notifications@github.com> wrote:

> @StuBez <https://github.com/StuBez>
> I am looking at POST api\samples at the description
> Why we should use an array there?
> What if I will send smthng like this
>
> {
>   sample_template_id: 10,
>   sample_instance_template_id: 2,
>   container_id: 22,
>   store_attributes: {
>         attribute1: value1,
>         attribute2: value2
>     },
>   posiitons: ["2:2", "3:10", "3:11", "3:12"],
>   colour: "#3300AA"
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/littlerobot/slims/issues/30#issuecomment-107128510>.
>

-- 


little robot Limited is a company registered in England and Wales. 
Registered number: 8923395. Registered office: CPC1, Capital Park, 
Fulbourn, Cambridgeshire, CB21 5XE.

**Comment by chuckn0rris** [comment]
@StuBez 

Does we need to have a grid with a list of samples we have at the moment? I imagine it like a grid and a button in the top bar 'Create new sample'.

I am talking about array of positions because we can add only the same samples for once, so there will be no difference, except for the position id. And we have no reasons to have an array of copy-pasted objects, isn't it?

**Comment by StuBez** [comment]
There will need to be a way for users to see a grid so they can see what
samples have been stored, yes. I'm not sure if there is an issue in GitHub
for that feature yet.

Selecting the grid positions and then clicking "Store samples" makes sense.

I can't check how you've implemented the store sample feature at the moment
but one of the requirements is that users need to be able to see the values
entered using the templates and be given an option to edit them. This is
bullet 4 in the "User process" section at the top of the page.

That means that the values for each sample that is stored will be slightly
different - it could be the comment has different words or a reference
number is different.

On Sunday, 31 May 2015, chuckn0rris <notifications@github.com> wrote:

> @StuBez <https://github.com/StuBez>
>
> Does we need to have a grid with a list of samples we have at the moment?
> I imagine it like a grid and a button in the top bar 'Create new sample'.
>
> I am talking about array of positions because we can add only the same
> samples for once, so there will be no difference, except for the position
> id. And we have no reasons to have an array of copy-pasted objects, isn't
> it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/littlerobot/slims/issues/30#issuecomment-107145955>.
>

-- 


little robot Limited is a company registered in England and Wales. 
Registered number: 8923395. Registered office: CPC1, Capital Park, 
Fulbourn, Cambridgeshire, CB21 5XE.

**Comment by chuckn0rris** [comment]
![idea](https://cloud.githubusercontent.com/assets/7203098/7901342/5487714e-07ad-11e5-885d-1693a3f78b59.png)

**Comment by chuckn0rris** [comment]
Interface video
http://screencast.com/t/66b7gf3zccI

**Comment by chuckn0rris** [comment]
@StuBez samples can be stored now!
But something wrong in `/samples` GET response - there is no `colour` field. Please, check it.

**Comment by chuckn0rris** [comment]
@StuBez `colour` field returns now. It was my fault
