### ISSUE TITLE
Create sample instance template

### ISSUE THREAD

**Issue by StuBez** [littlerobot/slims#32]
A sample instance template is a collection of attribute types. These attributes will be recorded by the user each time a sample is stored or removed from the container.

The possible options are:
* Attribute recorded when a sample is stored.
* Attribute recorded when a sample is removed.
* Attribute recorded when a sample is added _or_ removed.

I think this will work in a very similar way to the sample type templates.

# Data types
* **name**
  * String
  * 255 characters
  * Required
  * Must be unique in system
* **attributes**, array of:
	* **order**
	  * Integer
	  * Required
	* **label**
	  * String
	  * 255 characters
	  * Required
	  * Must be unique for the sample instance template
	* **type**
	  * One of:
	    * brief-text
	    * long-text
	    * option
	    * document
	    * date
	    * colour
	    * user
	* **display** (when to display the attribute)
	    * Array: `store`, `remove`
	    * OR, string: `store`, `remove`, `both`
	* **options** (only for `option` `type`)
	  * Array of strings
	  * 255 characters

How do you think would be best to store the `display` value?

# API
### Create with name only
`/api/sample-instance-template [POST]`
```json
{
  "name": "Template name"
}
```

### Create with name and attributes
`/api/sample-instance-template [POST]`
```json
{
  "name": "Template name",
  "attributes": {
    "store": [
      {
        "order": 1,
        "label": "Sex",
        "type": "option",
        "options": [
          "Male",
          "Female"
        ]
      },
      {
        "order": 2,
        "label": "Age",
        "type": "brief-text"
      },
      {
        "order": 3,
        "label": "Comment",
        "type": "long-text"
      },
      {
        "order": 4,
        "label": "Stored by",
        "type": "user"
      },
      {
        "order": 5,
        "label": "Date stored",
        "type": "date"
      }
    ]
  },
  "remove": [
    {
      "order": 1,
      "label": "Reason",
      "type": "long-text"
    },
    {
      "order": 2,
      "label": "Removed by",
      "type": "user"
    },
    {
      "order": 3,
      "label": "Date removed",
      "type": "date"
    }
  ]
}
```
> `attributes` is optional - it does not need to be provided when the template is created.

### Update with name only
`/api/sample-instance-template/[id] [POST]`
```json
{
  "name": "Template name"
}
```

### Update with name and attributes
`/api/sample-instance-template/[id] [POST]`
```json
{
  "name": "Template name",
  "attributes": {
    "store": [
      {
        "order": 1,
        "label": "Sex",
        "type": "option",
        "options": [
          "Male",
          "Female"
        ]
      },
      {
        "order": 2,
        "label": "Age",
        "type": "brief-text"
      },
      {
        "order": 3,
        "label": "Comment",
        "type": "long-text"
      },
      {
        "order": 4,
        "label": "Stored by",
        "type": "user"
      },
      {
        "order": 5,
        "label": "Date stored",
        "type": "date"
      }
    ]
  },
  "remove": [
    {
      "order": 1,
      "label": "Reason",
      "type": "long-text"
    },
    {
      "order": 2,
      "label": "Removed by",
      "type": "user"
    },
    {
      "order": 3,
      "label": "Date removed",
      "type": "date"
    }
  ]
}
```
## List
`/api/sample-instance-template [GET]`
```json
{
  "success": true,
  "sample_instance_templates": [
    {
      "name": "Template name",
      "attributes": {
        "store": [
          {
            "order": 1,
            "label": "Sex",
            "type": "option",
            "options": [
              "Male",
              "Female"
            ]
          },
          {
            "order": 2,
            "label": "Age",
            "type": "brief-text"
          },
          {
            "order": 3,
            "label": "Comment",
            "type": "long-text"
          },
          {
            "order": 4,
            "label": "Stored by",
            "type": "user"
          },
          {
            "order": 5,
            "label": "Date stored",
            "type": "date"
          }
        ]
      },
      "remove": [
        {
          "order": 1,
          "label": "Reason",
          "type": "long-text"
        },
        {
          "order": 2,
          "label": "Removed by",
          "type": "user"
        },
        {
          "order": 3,
          "label": "Date removed",
          "type": "date"
        }
      ]
    },
    {
      ...
    }
  ]
}
```
# Mockup
This is just an initial idea so please let me know what you think would work best. I think it will look more like the work you did on the [sample type templates](https://github.com/littlerobot/slims/issues/28) than the mockup below.

I had three ideas around specifying whether an attribute was for storing or removing a sample:
1. Create one template for adding and another one for removing samples. This is my least favourite.
2. For each attribute, have a checkbox to specify whether the attribute should be displayed when adding or removing a sample.
3. Always display certain attributes (user, date, operation.) Not at all flexible.

I think option 2 is the best of these options but let me know if you have any other thoughts.

![create sample instance template](https://cloud.githubusercontent.com/assets/910068/5892292/7929dbea-a4b1-11e4-9829-ff02715d4260.png)

# User process
1. The user creates a sample instance template.
2. When the user [stores](https://github.com/littlerobot/slims/issues/30) or [removes a sample](https://github.com/littlerobot/slims/issues/31), they choose the sample instance template (near the top of the page). This displays the fields that they must fill in (the bottom group of form elements).

Please see the two linked issues to see how the different parts might fit together.

**Comment by StuBez** [comment]
@chuckn0rris It is quite similar to the work you did last time but I think it is more complicated. Let me know if anything doesn't make sense to you.

I would like your ideas on the data types and UI the most but please share any ideas you have. Once these things are sorted, we will decide the API.

**Comment by StuBez** [comment]
They liked your prototype for configuring the attributes that would be displayed when storing and removing samples.

Some attributes would be displayed when adding *and* removing - date, user, etc. Others would only be displayed when adding a sample *or* removing it.

The API that I'm thinking of is:
`/api/sample-instance-template [POST]`
```json
{
  "name": "Template name",
  "attributes": {
    "store": [
      {
        "order": 1,
        "label": "Sex",
        "type": "option",
        "options": [
          "Male",
          "Female"
        ]
      },
      {
        "order": 2,
        "label": "Age",
        "type": "brief-text"
      },
      {
        "order": 3,
        "label": "Comment",
        "type": "long-text"
      },
      {
        "order": 4,
        "label": "Stored by",
        "type": "user"
      },
      {
        "order": 5,
        "label": "Date stored",
        "type": "date"
      }
    ]
  },
  "remove": [
    {
      "order": 1,
      "label": "Reason",
      "type": "long-text"
    },
    {
      "order": 2,
      "label": "Removed by",
      "type": "user"
    },
    {
      "order": 3,
      "label": "Date removed",
      "type": "date"
    }
  ]
}
```
It would be possible to create the template and then add the attributes separately, as you do with the existing templates.

What do you think?

**Comment by StuBez** [comment]
@chuckn0rris I have created a little of the create and list APIs. It is possible to create a template with just a name and list templates (only the name will be displayed.)

**Example list**
`/api/sample-instance-templates [GET]`
```json
{
  "success": true,
  "sample_instance_templates": [
    {
      "id": 1,
      "name": "Template name"
    }
  ]
}
```

**Example create**
`/api/sample-instance-templates [POST]`
```json
{
    "name": "Template name"
}
```

You will need to execute the database migrations: `php app/console doctrine:migrations:migrate -n`.

I will let you know when the other API functions are ready.

**Comment by StuBez** [comment]
The rest of the API is now developed so you can create templates and add and update attributes.

I haven't yet added any validation and there is an extra property (`activity`) in the attributes element that you can ignore. I will try to remove this later.

Please let me know if you find any problems and I will fix them.

**Comment by StuBez** [comment]
I've added the validation so this can be closed whenever the UI is using the APIs, @chuckn0rris.

**Comment by StuBez** [comment]
@chuckn0rris I have made a fix that solves the problem with deleting attributes. I think it may also fix the problem you had copying attributes.

**Comment by chuckn0rris** [comment]
@StuBez thanks, deleting and moving attributes features are fixed. But copying still have a problem. I think it is internal Ext JS problem, because I didn't do any customization for this behavior. Will try fix it.

**Comment by chuckn0rris** [comment]
I fixed d'n'd copying bug.
