### ISSUE TITLE
All types of templates can be archived

### ISSUE THREAD

**Issue by StuBez** [littlerobot/slims#33]
If a template is no longer valid (it may be out of date, for example) it should be possible to archive it.

* Any information that was recorded against the template will be kept and will be visible as normal.
* It will not be possible to select an archived template for a sample type or when storing or removing samples.

**Comment by chuckn0rris** [comment]
1. I think we need to add 'state' field to our Template class
state: [0, 1, 2], there 0 - can be edited, 1 - in use, 2 - archived.
2. I will filter templates list for comboboxes by 'state' and hide all archived for user to prevent selection.
3. I wll add an action 'Archive' near 'Edit' action for each Template in Templates grid. Here http://screencast.com/t/LKULkvpk1N

**Comment by StuBez** [comment]
I think that is correct. It's not something that needs to be developed now so we can ignore it. https://github.com/littlerobot/slims/milestones/v0.5 is all we need to work on at the moment.
