### ISSUE TITLE
Create a sample type

### ISSUE THREAD

**Issue by StuBez** [littlerobot/slims#36]
A sample type is a category of sample. Examples could be [mouse embryos](https://www.google.com/search?q=mouse+embryo&tbm=isch&tbo=u&source=univ&sa=X&ei=iEPXVMvpOIjW7Qbhl4G4Cw&ved=0CB4QsAQ&biw=1440&bih=769) or [human sperm](https://www.google.com/search?q=human+sperm&biw=1440&bih=769&source=lnms&tbm=isch&sa=X&ei=9EPXVL6ZB6TC7AajiYHwCA&ved=0CAYQ_AUoAQ).

Each sample type will have [sample type attributes](https://github.com/littlerobot/slims/issues/28) that are common to all the samples of that type. This would be things like the name, species, etc.

This page will allow a user to select a [sample type template](https://github.com/littlerobot/slims/issues/28) and provide values for each attribute.

A list of sample types (names) will be displayed on the page so that it is possible to see where the template has been used before.

# Data types
* **name**
  * String
  * 255 characters
  * Required
  * Must be unique in system
* **attributes**, array of:
	* **sample template attribute ID (from #28)**
	  * Integer.
	  * Required.
	* **filename (for file upload only)**
	  * String.
	  * 255 characters.
	  * Required (only if attribute is a file upload.)
	* **value**
	  * Text.
            * Dates in YYYY-MM-DD format.
            * File contents need to be base64 encoded.
          * Up to 16MB, including encoding.
	  * Required.

# API
## Create
`/api/sample-types [POST]`
```json
{
  "name": "Mouse embryos",
  "sample_type_template": 1,
  "attributes": [
    {
      "id": 1,
      "value": "Trypsin"
    },
    {
      "id": 2,
      "value": "Typice, tam asinos esset mortuis, sicut stupri frixam gallinaceo, sed tu accidere ad detrahendum hoc cacas Dum ego in a transeuntem, tempus sic non wanna te occidere, volo te adjuvet. Sed non hoc tibi, quod mihi non sunt. Praeterea, Ive 'iam fuerunt nimio cacas hoc mane super hoc casu eam tradere vestris mutum asinum."
    },
    {
      "id": 3,
      "filename": "spreadsheet.xls",
      "value": "base64 encoded file content"
    },
    {
      "id": 4,
      "value": "2015-02-01"
    }
  ]
}
```

## List
`/api/sample-types [GET]`
```json
{
  "success": true,
  "sample_types": [
    {
      "id": 10,
      "name": "Mouse embryos",
      "sample_type_template": 1,
      "attributes": [
        {
          "id": 12,
          "label": "Foo",
          "sample_type_template_attribute": 1,
          "value": "Trypsin"
        },
        {
          "id": 13,
          "label": "Bar",
          "sample_type_template_attribute": 2,
          "value": "Typice, tam asinos esset mortuis, sicut stupri frixam gallinaceo, sed tu accidere ad detrahendum hoc cacas Dum ego in a transeuntem, tempus sic non wanna te occidere, volo te adjuvet. Sed non hoc tibi, quod mihi non sunt. Praeterea, Ive 'iam fuerunt nimio cacas hoc mane super hoc casu eam tradere vestris mutum asinum."
        },
        {
          "id": 14,
          "label": "Baz",
          "sample_type_template_attribute": 3,
          "filename": "spreadsheet.xls",
          "url": "http://www.../spreadsheet.xls"
        },
        {
          "id": 15,
          "label": "FooBar",
          "sample_type_template_attribute": 4,
          "value": "2015-02-01",
        }
      ]
    },
    {
      ...
    }
  ]
}
```

## Get single type
`/api/sample-types/[id] [GET]`
```json
{
  "success": true,
  "sample_type": {
    "id": 10,
    "name": "Mouse embryos",
    "sample_type_template": 1,
    "attributes": [
      {
        "id": 12,
        "label": "Foo",
        "sample_type_template_attribute": 1,
        "value": "Trypsin"
      },
      {
        "id": 13,
        "label": "Bar",
        "sample_type_template_attribute": 2,
        "value": "Typice, tam asinos esset mortuis, sicut stupri frixam gallinaceo, sed tu accidere ad detrahendum hoc cacas Dum ego in a transeuntem, tempus sic non wanna te occidere, volo te adjuvet. Sed non hoc tibi, quod mihi non sunt. Praeterea, Ive 'iam fuerunt nimio cacas hoc mane super hoc casu eam tradere vestris mutum asinum."
      },
      {
        "id": 14,
        "label": "Baz",
        "sample_type_template_attribute": 3,
        "filename": "spreadsheet.xls",
        "url": "http://www.../spreadsheet.xls"
      },
      {
        "id": 15,
        "label": "FooBar",
        "sample_type_template_attribute": 4,
        "value": "2015-02-01",
      }
    ]
  }
}
```

## Get single sample type template
`/api/sample-type-templates/[id] [GET]`
```json
{
  "success": true,
  "sample_type_template": {
    "editable": true,
    "id": 1,
    "name": "Template name",
    "attributes": [
      {
        "id": 1,
        "order": 1,
        "label": "Sex",
        "type": "option",
        "options": [
          "Male",
          "Female"
        ]
      },
      {
        "id": 2,
        "order": 2,
        "label": "Age",
        "type": "brief-text"
      },
      {
        "id": 3,
        "order": 3,
        "label": "Comment",
        "type": "long-text"
      },
      {
        "id": 4,
        "order": 4,
        "label": "User",
        "type": "user",
        "options": [
          "Kyle Heath",
          "Lucas Freeman",
          "Melony C. Negron",
          "Russell R. Beebe"
        ]
      },
      {
        "id": 5,
        "order": 5,
        "label": "Technical data",
        "type": "document"
      }
    ]
  }
}
```

# Mockup
![create sample type](https://cloud.githubusercontent.com/assets/910068/6096425/bd9fb2aa-af87-11e4-9218-c6e023be85ba.png)

This is just an example of the elements I think need to be displayed. Design the UI as you think will work best.

# User process
1. User selects a previously created sample type template from a drop-down.
2. The UI elements are displayed based on the attribute types.
3. The user names the sample type and fills in the attribute values.
4. The sample type is saved and becomes available to select when [storing](https://github.com/littlerobot/slims/issues/30) or [removing](https://github.com/littlerobot/slims/issues/31) a sample.

# To do
- [x] Create sample type API endpoint
- [x] List sample types API endpoint
- [x] Get sample type API endpoint
- [x] Get sample type template API endpoint

**Comment by StuBez** [comment]
I have created https://github.com/littlerobot/slims/tree/feature/36-create-a-sample-type to keep this functionality together. I will add the get single sample type template API today.

**Comment by StuBez** [comment]
The `options` for `user` attribute types are now populated. Here is an example:

`/api/sample-type-templates/[id] [GET]`
```json
{
  "success": true,
  "sample_type_template": {
    "editable": true,
    "id": 4,
    "name": "Template",
    "attributes": [
      {
        "id": 13,
        "order": 1,
        "label": "List",
        "type": "option",
        "options": [
          "First first",
          "Second second"
        ]
      },
      {
        "id": 14,
        "order": 2,
        "label": "Second",
        "type": "user",
        "options": [
          "Beryl Abshire PhD",
          "Dr. Agustina Barrows Sr.",
          "Dr. Carmel Sipes III",
          "Marie Gutkowski",
          "Miss Crystel Schroeder DDS",
          "New User",
          "Phyllis Smitham II",
          "Prof. Noble Littel",
          "Raegan Sauer",
          "Tre Strosin",
          "Waino Orn"
        ]
      },
      {
        "id": 15,
        "order": 3,
        "label": "Third",
        "type": "document"
      },
      {
        "id": 16,
        "order": 4,
        "label": "First",
        "type": "option",
        "options": [
          "test 1",
          "test"
        ]
      }
    ]
  }
}
```

**Comment by StuBez** [comment]
The create sample type API endpoint has now been created and includes validation. I have tried to update this examples at the top of the page so that they match the current API. Please let me know if you notice any parts that I have missed.

I have made quite a few changes so you will need to do the following:
1. `composer install --prefer-dist` to update the libraries.
2. `php app/console doctrine:migrations:migrate -n` to update the database schema.

If any of the responses do not look correct after doing this, please delete all folders in the `app/cache` directory and try again.

**Comment by chuckn0rris** [comment]
@StuBez 

List
/api/sample-types [GET]

I think we need to add attributes names to response ('name' field into 'attributes' array), if you want to display information about attributes in sample types grid, or we can remove 'value' field, if you doesn't.
I am about dysplaying SampleName: { attrName: value1, attrName2: value2 }
Or you want to display only values there?

**Comment by chuckn0rris** [comment]
@StuBez 
http://try.sencha.com/extjs/4.0.7/examples/grid/grid-plugins/
look at the first grid (Expander rows in a collapsible grid)
What about using this plugin for sample types grid?

**Comment by StuBez** [comment]
@chuckn0rris Yes, I think you're right about including the `name` field. I hadn't thought about that before. I will add that when I get time.

The grid looks good. Happy for you to use that if you think it will work well!

**Comment by StuBez** [comment]
@chuckn0rris I've added a `label` property to the API response. I hope that is the information you need.

**Comment by chuckn0rris** [comment]
@StuBez 
About composer install steps.
I had to run 'composer update' before that, because it did not work

**Comment by chuckn0rris** [comment]
Also I rebased a branch by current 'develop' branch

**Comment by chuckn0rris** [comment]
@StuBez  Cannot to do migration.
http://screencast.com/t/uR0GfjgzMXf9
app/cache tryied, but unsuccessfully

**Comment by StuBez** [comment]
@chuckn0rris Did you rebase to get the work from develop? That should be fine.

Was there an error message when you ran composer install? Doing an update should be OK as long as you don't commit the composer files.

I'm not sure why the migration isn't running. Your database must be different than mine was. Two things:
1. Are you able to make a SQL dump of your database and send it to me, or upload it, so I can see why the migration doesn't work?
2. If you need to sort it quickly, you could delete all tables and run migrations. You would need to recreate all data, though, which may take a long time.

I'm not at my computer now but I'll look at this some more when I am.

**Comment by chuckn0rris** [comment]
@StuBez I fully recreated DB but error is still there. 
Also I cannot log in. I think I forgot something, but I did all by readme in our main page
(of course with php app/console doctrine:migrations:migrate -n   command)

**Comment by chuckn0rris** [comment]
@StuBez Look at this when I will be available. it is not urgent

**Comment by StuBez** [comment]
@chuckn0rris Thanks for the extra information. I will look at the database problem when I can. Try running `php app/console doctrine:doctrine:fixtures:load` - this will create the users, and some other data.

**Comment by StuBez** [comment]
@chuckn0rris I've fixed the database migration - I was missing a statement to rename a table. I hope that fixes everything for you.

**Comment by chuckn0rris** [comment]
@StuBez yes, now all works fine! Thank you!

**Comment by chuckn0rris** [comment]
- [ ] Save type - window, behavior
- [ ] Edit type - behavior
- [ ] Update types attributes in grid
- [ ] Store/remove sample applying - UI, behavior

**Comment by chuckn0rris** [comment]
@StuBez in list */api/sample-types [GET]*
as root for items you using *sample_type* instead of *sample_types*

**Comment by StuBez** [comment]
@chuckn0rris

1. Fixed in 7c19767.
2. I had it like that at first but changed it because it looked a bit messy and #7 does not have an `_id` for `parent` or `research_group`. I can make the change you asked for if it makes your work easier. Please let me know.

**Comment by StuBez** [comment]
@chuckn0rris I don't know if you saw my message (https://github.com/littlerobot/slims/issues/36#issuecomment-77935948). Please let me know if you need anything changed.

**Comment by chuckn0rris** [comment]
@StuBez 
We doesn't have `_id` there.The problem is that I'm using the data model (REST). It would be convenient for me to use it to receive and store data without extra constraints on the field.
We using `parent` and `research_group` everywhere - then I getting and then I saving. Let's use 'sample_type_template' instead of `sample_type_template_id` everywhere and it's will be fine.

I recieve data:
`
{
   id: 12,
   name: 'Name',
   sample_type_template: 33,
   attributes: [...]
}
`

But for save it I must cange it:
`
type.sample_type_template_id = type.sample_type_template;
delete type.sample_type_template;
`

**Comment by StuBez** [comment]
@chuckn0rris The latest commit should change all the element names to how you want. Please let me know if I missed any.

I made a mistake before with a database column name so there is a migration to fix that. You should run `php app/console doctrine:migrations:migrate -n`.

**Comment by chuckn0rris** [comment]
@StuBez I executed `php app/console doctrine:migrations:migrate -n` command, but got 'No migrations to execute' message

**Comment by chuckn0rris** [comment]
@StuBez 
I want ask about 4th item of list. How it will looks like? 
![2015-03-21_1734](https://cloud.githubusercontent.com/assets/7203098/6764700/d0c5cb7e-cff0-11e4-8850-5087bca18e16.png)

**Comment by StuBez** [comment]
I think I forgot to commit the migration. I will fix that today.

My idea on how those pages would look are in the linked GitHub issues but they do not have to look exactly like that - I'm happy for you to help decide.

**Comment by StuBez** [comment]
The update sample type endpoint now exists: `/api/sample-types/[id] [POST]`. The format is the same as create sample type.

**Comment by chuckn0rris** [comment]
@StuBez 
 Cannot create saple-instance-template - error 500 - "Attempted to load class "SampleInstanceStoredTemplateAttributeType" from namespace "Cscr\SlimsApiBundle\Form\Typ

**Comment by chuckn0rris** [comment]
[ ] - Color picker
 [ ] - Document picker

**Comment by chuckn0rris** [comment]
@StuBez We need to deside which erorrs format we will using. 
Some errors returns like errors: [ errors: ["here message"] ]
And some like: errors: [ children: [ colour: [ errors: ["here message"] ] ] ]
So, I think we need to use something that I can handle for showing error message in a window.

**Comment by StuBez** [comment]
What URL are you POSTing to and what message are you sending?

On Friday, 3 April 2015, chuckn0rris <notifications@github.com> wrote:

> @StuBez <https://github.com/StuBez>
> Cannot create saple-instance-template - error 500 - "Attempted to load
> class "SampleInstanceStoredTemplateAttributeType" from namespace
> "Cscr\SlimsApiBundle\Form\Typ
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/littlerobot/slims/issues/36#issuecomment-89139357>.
>

-- 


little robot Limited is a company registered in England and Wales. 
Registered number: 8923395. Registered office: CPC1, Capital Park, 
Fulbourn, Cambridgeshire, CB21 5XE.

**Comment by StuBez** [comment]
I think the error messages are in the same format as they have been for
other API end points.  The error message format may be more complicated
because of that. Can you give an example of the message you sent and the
errors you got back so I can see?

On Friday, 3 April 2015, chuckn0rris <notifications@github.com> wrote:

> @StuBez <https://github.com/StuBez> We need to deside which erorrs format
> we will using.
> Some errors returns like errors: [ errors: ["here message"] ]
> And some like: errors: [ children: [ colour: [ errors: ["here message"] ]
> ] ]
> So, I think we need to use something that I can handle for showing error
> message in a window.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/littlerobot/slims/issues/36#issuecomment-89151408>.
>

-- 


little robot Limited is a company registered in England and Wales. 
Registered number: 8923395. Registered office: CPC1, Capital Park, 
Fulbourn, Cambridgeshire, CB21 5XE.

**Comment by chuckn0rris** [comment]
POST
{"name":"asds"}
http://localhost:8000/app_dev.php/api/sample-instance-templates

About error messages. Yes, they has the same format, but this format is not easy to parse. I think we should use something not so complicated to be parced

Example - I sent bad color format - without '#', now it cannot be reproduced.
I think it is not important that I sent, because message about form errors always looks like 
errors: [ children: [ fieldName: [ "erorr message" ], filedName1: [ "error message 2" ] ] ]
Can you sent something like:
errors: [ {errorId: 'DATA_FORMAT_ERROR', filedName: 'color', message: 'incorrect data format'} ]
so, if I will have errorId, I can use another description, more userfriendly, if it will be necessary

**Comment by chuckn0rris** [comment]
@StuBez 
Here an example of error message I recieved now
{"code":400,"message":"Validation Failed","errors":{"children":{"name":[],"sample_type_template":[],"attributes":{"children":[{"children":{"id":[],"value":[],"mime_type":[],"filename":[]}},{"children":{"id":[],"value":[],"mime_type":[],"filename":[]}},{"children":{"id":[],"value":[],"mime_type":[],"filename":[]}},{"children":{"id":[],"value":[],"mime_type":[],"filename":[]}},{"children":{"id":[],"value":[],"mime_type":[],"filename":[]}},{"children":{"id":[],"value":[],"mime_type":[],"filename":[]}},{"children":{"id":[],"value":{"errors":["The attribute must have a value."]},"mime_type":{"errors":["A document must have a MIME type."]},"filename":{"errors":["A document must have a filename."]}}}]}}}}

**Comment by chuckn0rris** [comment]
Now all works fine if sample template hasn't document type field. 
I stopped on file uploading. It is not trivial task

**Comment by StuBez** [comment]
It is not easy to change the error format - it is how the framework makes the errors by default. It would also mean that you would have to change all the other error parsing that you have already written?

I will check to see how important it is for people to be able to upload documents. Perhaps it is not something they need very much and could be ignored.

**Comment by chuckn0rris** [comment]
`It would also mean that you would have to change all the other error parsing that you have already written?`
I have only one place there I handle all errors and my parse fuction now - 2 'if' statements :)

**Comment by StuBez** [comment]
Are we still OK leave it how it is for now and try to make it better later?

**Comment by chuckn0rris** [comment]
Yes. It is just for information

**Comment by chuckn0rris** [comment]
![load_file](https://cloud.githubusercontent.com/assets/7203098/6981619/ddb13d44-da2e-11e4-979d-9b58554ef7a4.png)
@StuBez 
Now we can upload a file. Also we have download link in the grid. But we need to fix a situation when we editing a `sample type` with already uploaded file. I talking about a possible to save form without setting `document` field. Now I have an error after attempt to edit a sample type without selecting a file. But I think it isn't right behavior, isn't it?

**Comment by StuBez** [comment]
I think I understand the problem - if you edit a sample type where a
document was uploaded before, it returns an error if you keep the document
field but don't upload a file again? I will try to fix that problem today
or tomorrow.

On 3 April 2015 at 12:33, chuckn0rris <notifications@github.com> wrote:

> [image: load_file]
> <https://cloud.githubusercontent.com/assets/7203098/6981619/ddb13d44-da2e-11e4-979d-9b58554ef7a4.png>
> @StuBez <https://github.com/StuBez>
> Now we can upload a file. Also we have download link in the grid. But we
> need to fix a situation when we editing a sample type with already
> uploaded file. I talking about a possible to save form without setting
> document field. Now I have an error after attempt to edit a sample type
> without selecting a file. But I think it isn't right behavior, isn't it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/littlerobot/slims/issues/36#issuecomment-89261289>.
>

-- 


little robot Limited is a company registered in England and Wales. 
Registered number: 8923395. Registered office: CPC1, Capital Park, 
Fulbourn, Cambridgeshire, CB21 5XE.

**Comment by chuckn0rris** [comment]
Yes, it is

**Comment by StuBez** [comment]
@chuckn0rris I just started to look into the document problem but I can't add a document in the UI - it doesn't send the MIME type when I try to upload it. Should this work? I may be able to calculate the MIME type on the server side if this is a problem for you.
![screen shot 2015-04-03 at 17 13 24](https://cloud.githubusercontent.com/assets/910068/6984832/e40248fa-da24-11e4-8744-86fc6f54c089.png)

There is also a strange path in the input. Does it need to be like this?
![screen shot 2015-04-03 at 17 13 33](https://cloud.githubusercontent.com/assets/910068/6984838/eba7d9da-da24-11e4-81e1-2d925a6e55aa.png)

**Comment by chuckn0rris** [comment]
@StuBez 
About mime type. I just take it from file's info (file.type property). So, I think you should to calculate mime type on the server if I sent you empty.
About path. Path cannot be real by browser's security reasons. So, it is OK. http://stackoverflow.com/questions/4851595/how-to-resolve-the-c-fakepath

**Comment by chuckn0rris** [comment]
@StuBez Let's try to upload a normal file, with a known extension (ex .jpg). It must be possible without problems

**Comment by StuBez** [comment]
Thanks for explaining that. I think calculating the MIME type on the server
makes sense so I will make that change today.

Is it possible to not display the file path in the browser at all? I think
it could be a bit confusing for users.

On Saturday, 4 April 2015, chuckn0rris <notifications@github.com> wrote:

> @StuBez <https://github.com/StuBez>
> About mime type. I just take it from file's info (file.type property). So,
> I think you should to calculate mime type on the server if I sent you empty.
> About path. Path cannot be real by browser's security reasons. So, it is
> OK.
> http://stackoverflow.com/questions/4851595/how-to-resolve-the-c-fakepath
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/littlerobot/slims/issues/36#issuecomment-89495096>.
>

-- 


little robot Limited is a company registered in England and Wales. 
Registered number: 8923395. Registered office: CPC1, Capital Park, 
Fulbourn, Cambridgeshire, CB21 5XE.

**Comment by chuckn0rris** [comment]
I think I'll do it today - try to trim a path from a field

**Comment by StuBez** [comment]
I am now setting the MIME type on the server so you can stop sending that from the client. I have made `mime_type` optional now but will remove it from the API once you have changed the JS not to send it.

Allowing the document not to be uploaded again when editing the sample type is not trivial. Do you need that change to be made or can we leave it that the user will have to upload the document if they edit a sample type? If that is OK for you, I will check with the users to see if this is a problem.

I think that would also mean we wouldn't need the "Remove existing document" checkbox.
