### ISSUE TITLE
Incorrect number of sample spaces displayed in UI

### ISSUE THREAD

**Issue by StuBez** [littlerobot/slims#42]
To reproduce:

1. Create a new sample container with 2 row and 10 columns.
2. Select the container.
3. The grid on the top-right of the page displays **3** rows and 10 columns.

This is the response from the API:
```json
{
      "leaf": true,
      "sample_remaining_capacity": 20,
      "sample_total_capacity": 20,
      "samples_stored": 0,
      "id": 124,
      "name": "Test",
      "rows": 2,
      "columns": 10,
      "stores": "samples",
      "colour": "#FFFFFF",
      "data": []
}
```

![screen shot 2015-06-28 at 15 30 03](https://cloud.githubusercontent.com/assets/910068/8396723/97e76846-1daa-11e5-9718-c21a0f43a16e.png)

**Comment by chuckn0rris** [comment]
Fixed
