### ISSUE TITLE
Wording changes

### ISSUE THREAD

**Issue by StuBez** [littlerobot/slims#44]
Just some small text changes.

<img width="696" alt="screen shot 2015-07-04 at 11 56 35" src="https://cloud.githubusercontent.com/assets/910068/8507687/b327d9d0-2244-11e5-966f-f59c28a1bd8b.png">
> Please remove the "Sample storing here" text in the popup - the two bottom lines are enough information.
> Please change "Select Posititons for storing new Samples" to "Select empty positions to store samples".

<img width="617" alt="screen shot 2015-07-04 at 12 02 26" src="https://cloud.githubusercontent.com/assets/910068/8507690/c2abe8d8-2244-11e5-9b86-cbb52216c8d5.png">
> Please make the text "Select the sample type".

<img width="615" alt="screen shot 2015-07-04 at 11 57 31" src="https://cloud.githubusercontent.com/assets/910068/8507695/d62e2038-2244-11e5-9600-2a3670930b65.png">
> Please make the text "Select the template".

<img width="623" alt="screen shot 2015-07-04 at 11 58 26" src="https://cloud.githubusercontent.com/assets/910068/8507675/6bed18f0-2244-11e5-9351-76ccaab81042.png">
> Please change "Store attribute fields" to "Attributes"

<img width="1435" alt="screen shot 2015-07-04 at 11 59 42" src="https://cloud.githubusercontent.com/assets/910068/8507669/30d22990-2244-11e5-9bb2-dc835f3d720e.png">
> Can me middle text just say "Drag attributes to change their order".

**Comment by suzzopher** [comment]
All looks good.
