### ISSUE TITLE
Search for samples

### ISSUE THREAD

**Issue by StuBez** [littlerobot/slims#47]
It should be possible for users to search for samples that are stored in the system.

Initial search criteria (these are all sample instance attributes):
* Search by sample name
* Search by user (partial name)
* Search by date stored (range)
* Search by type of sample
* Search by container name

To make this work, the above attributes will be added to the templates when the users create them. They will be responsible for ensuring this happens and there will be no system functionality to enforce this.

They would like to be able to choose which attributes to display in the table. Possibly using the column chooser in the data grid after the results are returned?

Searches could return samples with different attributes so some cells could be blank.

**Comment by chuckn0rris** [comment]
```json
{
"success": true,
"data": [{
    "container": 5,
    "containerName": "Floor 4",
    "row": 7,
    "column": 7,
    "colour": "#451322",
    "sampleType": 22,
    "sampleTypeName": "Mouse Mickey",
    "name": "Sample Name",
    "sampleTemplate": 31,
    "sampleTemplateName": "Template Name",
    "attributes": [
      {
        "id": 12,
        "label": "City",
        "value": "Los Angeles"
      },
      {
        "id": 1,
        "label": "Attached map",
        "filename": "Manufacturer information.pdf",
        "mime_type": "application/pdf",
        "value": "<base 64 encoded file content>"
      }
    ]
  }, {...}]
}
```

First of all we should have user-friendly names in the response for all fields what we need to show.

**Comment by chuckn0rris** [comment]
<img width="1362" alt="2015-07-21_2324" src="https://cloud.githubusercontent.com/assets/7203098/8806179/9ff8f470-2fff-11e5-9bd2-b5f33931f66e.png">
Advanced panel hidden by default and collapsed on click 'Advanced'
Also, I think main search query field should be disabled or hidden when advanced mode on. And I will add 'Search' button at the bottom of advanced panel.
What do you think?

**Comment by StuBez** [comment]
I've got the beginnings of the filter API:

`GET /samples/filter?name=xxx&type=xxx&user=xxx&container=xxx&stored_from=xxx&stored_to=xxx`
_All of the query parameters are optional - you can send as many as you want_

I have not had time to customise the response so it is just the default. I've added a `GET /samples/dummy` route that returns your example JSON. You can change the JSON by editing https://github.com/littlerobot/slims/blob/feature/47-search-samples/src/Cscr/SlimsApiBundle/Controller/SamplesController.php#L47-L79

I think there may need to be some changes for the structure of the attributes if they have a file (it will need a link to download the file and the file content is not helpful to you) but I will try to make it look like your suggestion.

**Comment by StuBez** [comment]
The filter API is now complete - all the filters should work as expected. The date format is dd/mm/yyyy.

The response is almost as you requested:
```json
{
  "success": true,
  "results": [
    {
      "container": 4,
      "container_name": "Wedge 1",
      "row": 3,
      "column": 0,
      "colour": "#FFFFFF",
      "type": 1,
      "type_name": "Sally's mouse embryos",
      "instance_template": 3,
      "instance_template_name": "Filter test",
      "instance_attributes": [
        {
          "id": 32,
          "label": "Staff",
          "type": "user",
          "value": "Test user"
        },
        {
          "id": 33,
          "label": "Name",
          "type": "brief-text",
          "value": "Sample name"
        },
        {
          "id": 34,
          "label": "Stored",
          "type": "date",
          "value": "06\\/08\\/2015"
        }
      ],
      "type_attributes": [
        {
          "id": 1,
          "label": "Type",
          "type": "brief-text",
          "value": "Embryotech Laboratories"
        },
        {
          "id": 2,
          "label": "Genus",
          "type": "brief-text",
          "value": "Mus"
        },
        {
          "id": 3,
          "label": "Notes",
          "type": "long-text",
          "value": "N\\/A"
        }
      ]
    },
    {
      "container": 4,
      "container_name": "Wedge 1",
      "row": 4,
      "column": 0,
      "colour": "#FFFFFF",
      "type": 1,
      "type_name": "Sally's mouse embryos",
      "instance_template": 3,
      "instance_template_name": "Filter test",
      "instance_attributes": [
        {
          "id": 35,
          "label": "Staff",
          "type": "user",
          "value": "Test user"
        },
        {
          "id": 36,
          "label": "Name",
          "type": "brief-text",
          "value": "Sample name"
        },
        {
          "id": 37,
          "label": "Stored",
          "type": "date",
          "value": "06\\/08\\/2015"
        }
      ],
      "type_attributes": [
        {
          "id": 1,
          "label": "Type",
          "type": "brief-text",
          "value": "Embryotech Laboratories"
        },
        {
          "id": 2,
          "label": "Genus",
          "type": "brief-text",
          "value": "Mus"
        },
        {
          "id": 3,
          "label": "Notes",
          "type": "long-text",
          "value": "N\\/A"
        }
      ]
    },
    {
      "container": 4,
      "container_name": "Wedge 1",
      "row": 5,
      "column": 0,
      "colour": "#FFFFFF",
      "type": 1,
      "type_name": "Sally's mouse embryos",
      "instance_template": 3,
      "instance_template_name": "Filter test",
      "instance_attributes": [
        {
          "id": 38,
          "label": "Staff",
          "type": "user",
          "value": "Staff"
        },
        {
          "id": 39,
          "label": "Name",
          "type": "brief-text",
          "value": "Name"
        },
        {
          "id": 40,
          "label": "Stored",
          "type": "date",
          "value": "06\\/08\\/2015"
        },
        {
          "id": 41,
          "label": "File",
          "type": "document"
        }
      ],
      "type_attributes": [
        {
          "id": 1,
          "label": "Type",
          "type": "brief-text",
          "value": "Embryotech Laboratories"
        },
        {
          "id": 2,
          "label": "Genus",
          "type": "brief-text",
          "value": "Mus"
        },
        {
          "id": 3,
          "label": "Notes",
          "type": "long-text",
          "value": "N\\/A"
        }
      ]
    },
    {
      "container": 7,
      "container_name": "Wedge 4",
      "row": 4,
      "column": 5,
      "colour": "#FFFFFF",
      "type": 1,
      "type_name": "Sally's mouse embryos",
      "instance_template": 3,
      "instance_template_name": "Filter test",
      "instance_attributes": [
        {
          "id": 42,
          "label": "Staff",
          "type": "user",
          "value": "Test"
        },
        {
          "id": 43,
          "label": "Name",
          "type": "brief-text",
          "value": "Test"
        },
        {
          "id": 44,
          "label": "Stored",
          "type": "date",
          "value": "06\\/08\\/2015"
        },
        {
          "id": 45,
          "label": "File",
          "type": "document"
        }
      ],
      "type_attributes": [
        {
          "id": 1,
          "label": "Type",
          "type": "brief-text",
          "value": "Embryotech Laboratories"
        },
        {
          "id": 2,
          "label": "Genus",
          "type": "brief-text",
          "value": "Mus"
        },
        {
          "id": 3,
          "label": "Notes",
          "type": "long-text",
          "value": "N\\/A"
        }
      ]
    }
  ]
}
```

I will add the document fields once #48 and #49 are fixed - I can't easily check the output at the moment.

Please let me know if there are any changes you need me to make.

**Comment by StuBez** [comment]
I gave the incorrect URL. It is: `GET /samples?name=xxx&type=xxx&user=xxx&container=xxx&stored_start=xxx&stored_end=xxx`

**Comment by chuckn0rris** [comment]
I have an error if I searching by Sample Type (type param name)
```
{
  "code":500,
  "message":"[Semantical Error] line 0, col 413 near 'sample_type_template_attributes': Error: 'sample_type_template_attributes' is already defined."
}
```

When type is empty - all work good
UI works now for searching. But I don’t added saving columns visible. So, you can see results of your search

**Comment by chuckn0rris** [comment]
What about use clear button in every field of a filter? 
Please, look at example: http://www.eekboom.de/ClearButton.html

**Comment by StuBez** [comment]
Yes, a clear button would be good, I think.

**Comment by chuckn0rris** [comment]
Added `clear button` for all fields in search filter panel

**Comment by chuckn0rris** [comment]
@StuBez 
Cannot add Instance Template
Request URL: http://slims.dev/app_dev.php/api/sample-instance-templates
Request Method: POST
Status Code: 200 OK
{"name":"new"}

Response:
{"success":true,"sample_instance_template":{"id":7,"name":"new","store":[],"remove":[]}}

But I don't see this template in the list on 
Request URL: http://slims.dev/app_dev.php/api/sample-instance-templates
Request Method: GET

**Comment by StuBez** [comment]
@chuckn0rris 

I had changed the query because you were not showing templates when adding a sample unless they had store and remove attributes. I had forgotten we need to see them if they don't have any attributes when we are creating them. Now fixed.

**Comment by StuBez** [comment]
Is this ready for me to merge into `develop` now?

**Comment by chuckn0rris** [comment]
@StuBez no, I still working here. 
I fixed a few bugs with saving files and setting colors, edited color renderer, did small refactoring in components for reusing. But I still working on search results state saving

**Comment by chuckn0rris** [comment]
@StuBez looks like stored_from and stored_to dates filters works only together. If I specified one of them - server returns me full set of data.
Also it is possible to do searching with empty filter. I am not sure it is good. Maybe we should add rules there? Min length for typed text, required 1 or 2 fields, etc..

**Comment by StuBez** [comment]
Yes, both dates are required at the moment. I will check with the users to see if that is correct.

You are right about the searching with no filters. I will fix that.

**Comment by chuckn0rris** [comment]
@StuBez I've added validation. I've added minLength = 3 for all text fields and have prevented search if only 1 date field was filled.
But it looks like searching works incorrectly. I have results only if I using _Container name_ field. Results are empty if I used dates, user name, or any other 1 field or together with container name. 
Please, check it!
