### ISSUE TITLE
Documents are not sent as part of storing a sample

### ISSUE THREAD

**Issue by StuBez** [littlerobot/slims#48]
If I select a document when storing a sample, it is not sent as part of the request.

<img width="637" alt="screen shot 2015-08-06 at 15 38 41" src="https://cloud.githubusercontent.com/assets/910068/9114373/6791d29c-3c51-11e5-8fc0-4a18cc450641.png">
<img width="749" alt="screen shot 2015-08-06 at 15 38 46" src="https://cloud.githubusercontent.com/assets/910068/9114374/697db3f0-3c51-11e5-84ce-b091bccffbd5.png">
<img width="963" alt="screen shot 2015-08-06 at 15 39 18" src="https://cloud.githubusercontent.com/assets/910068/9114377/6ab1acea-3c51-11e5-8a7c-70bb450e0f47.png">

**Comment by chuckn0rris** [comment]
Fixed
