### ISSUE TITLE
Document not correctly sent when creating sample type

### ISSUE THREAD

**Issue by StuBez** [littlerobot/slims#49]
The file name is being sent as the `value` (which is not correct) and no document content is being sent. [Issue 36](https://github.com/littlerobot/slims/issues/36) has details of the correct format.

<img width="1124" alt="screen shot 2015-08-06 at 15 44 11" src="https://cloud.githubusercontent.com/assets/910068/9114484/16a4c3fc-3c52-11e5-8f2d-954ba9d2bb7b.png">

**Comment by chuckn0rris** [comment]
Fixed
