### ISSUE TITLE
Display error messages to user

### ISSUE THREAD

**Issue by StuBez** [littlerobot/slims#52]
The API returns error messages with details of what the user needs to fix to make a successful request.

These should be displayed in the UI but they **do not** have to be displayed in the form - whatever is not too hard to write and is clear to users.

> **Note**: There could be more than one error per attribute.

Examples of the responses:
`POST /api/users`
```json
{
  "code": 400,
  "message": "Validation Failed",
  "errors": {
    "children": {
      "name": {
        "errors": [
          "Name cannot be blank."
        ]
      },
      "username": {
        "errors": [
          "This user has already been added."
        ]
      },
      "research_group": [],
      "is_active": []
    }
  }
}
```

`POST /api/containers`
```json
{
  "code": 400,
  "message": "Validation Failed",
  "errors": {
    "children": {
      "name": {
        "errors": [
          "The container must have a name."
        ]
      },
      "parent": [],
      "research_group": [],
      "rows": {
        "errors": [
          "The number of rows must be specified."
        ]
      },
      "columns": {
        "errors": [
          "The number of columns must be specified."
        ]
      },
      "stores": {
        "errors": [
          "What the container stores must be specified."
        ]
      },
      "comment": [],
      "colour": []
    }
  }
}
```

I can provide more examples if it is needed.

**Comment by chuckn0rris** [comment]
<img width="888" alt="2015-08-29_2339" src="https://cloud.githubusercontent.com/assets/7203098/9563215/3f5b0f74-4ea7-11e5-8e2b-135d2d74700c.png">

**Comment by chuckn0rris** [comment]
<img width="913" alt="2015-08-29_2341" src="https://cloud.githubusercontent.com/assets/7203098/9563234/87a38194-4ea7-11e5-8df5-a32a4ee5af77.png">
I removed icon, what do you think?

**Comment by StuBez** [comment]
I really like it. Is it possible to remove the "Error appeared" title?

Now you have added the messages, I will re-write them to be clearer.

**Comment by chuckn0rris** [comment]
Done
