### ISSUE TITLE
Rows and columns switched in container display

### ISSUE THREAD

**Issue by StuBez** [littlerobot/slims#53]
A container with 10 rows and 11 columns is being displayed with 10 columns and 11 rows.

<img width="855" alt="screen shot 2015-09-07 at 13 12 53" src="https://cloud.githubusercontent.com/assets/910068/9716499/3792293c-5562-11e5-8a33-c21100bd6b9e.png">
<img width="457" alt="screen shot 2015-09-07 at 13 13 03" src="https://cloud.githubusercontent.com/assets/910068/9716500/37969ada-5562-11e5-8df6-4290390009e5.png">

**Comment by chuckn0rris** [comment]
@StuBez I've tried to create container but have recieved an error
```
{"code":500,"message":"The option \"choice_label\" does not exist. Known options are: \"action\", \"allow_extra_fields\", \"attr\", \"auto_initialize\", \"block_name\", \"by_reference\", \"cascade_validation\", \"choice_list\", \"choices\", \"class\", \"compound\", \"constraints\", \"csrf_field_name\", \"csrf_message\", \"csrf_protection\", \"csrf_provider\", \"csrf_token_id\", \"csrf_token_manager\", \"data\", \"data_class\", \"disabled\", \"em\", \"empty_data\", \"empty_value\", \"error_bubbling\", \"error_mapping\", \"expanded\", \"extra_fields_message\", \"group_by\", \"inherit_data\", \"intention\", \"invalid_message\", \"invalid_message_parameters\", \"label\", \"label_attr\", \"label_format\", \"loader\", \"mapped\", \"max_length\", \"method\", \"multiple\", \"pattern\", \"placeholder\", \"post_max_size_message\", \"preferred_choices\", \"property\", \"property_path\", \"query_builder\", \"read_only\", \"required\", \"translation_domain\", \"trim\", \"validation_groups\", \"virtual\"."}
```
My request:
http://slims.dev/app_dev.php/api/containers
POST
name:RowColumnsTest
comment:
colour:#99CC00
parent:3
research_group:
rows:10
columns:4
stores:samples

**Comment by StuBez** [comment]
Can you try running `composer install --prefer-dist`? I updated the framework and I think one of the changes is causing this problem.

**Comment by chuckn0rris** [comment]
@StuBez yep, it's helped me, thank you!

**Comment by suzzopher** [comment]
This is now showing as 10 rows and 11 columns 
![screen shot 2015-09-23 at 21 19 08](https://cloud.githubusercontent.com/assets/173174/10057561/d43ec5b4-6238-11e5-8e8c-7b93a260a140.png)

Have also tried multiple different number combinations and all look good.
