### ISSUE TITLE
Search result column widths should display all content

### ISSUE THREAD

**Issue by StuBez** [littlerobot/slims#54]
Is it possible to make the columns as wide as the content so that users do not have to resize the columns each time they run a search?

**Comment by chuckn0rris** [comment]
@StuBez no, we haven't tools to do this. 
But we can have special width for every type of attributes - 
for example:
brief-text - 50px
long-text - 150px
date - 80px
...
What do you think?

**Comment by StuBez** [comment]
That's a shame, I hoped we could use http://docs.sencha.com/extjs/4.2.0/#!/api/Ext.grid.column.Column-method-autoSize

If that isn't possible, setting those widths would make things better.

**Comment by chuckn0rris** [comment]
I pushed my decision for this feature. I also added a tooltip for long-text columns, if text length > 40 letters.

**Comment by suzzopher** [comment]
Yep looks good.
