### ISSUE TITLE
Allow scrolling when adding a sample

### ISSUE THREAD

**Issue by StuBez** [littlerobot/slims#55]
The "Sample Wizard Tool" dialog is not always tall enough to display all content and needs to be manually resized.

Can the dialog be scrollable?

<img width="716" alt="screen shot 2015-09-07 at 13 33 26" src="https://cloud.githubusercontent.com/assets/910068/9716801/595d6bbe-5565-11e5-8c39-8b582e035ddb.png">

**Comment by chuckn0rris** [comment]
@StuBez I've tried to add attribute to my Type Template and recieved an error:
```
{"code":500,"message":"The form's view data is expected to be of type scalar, array or an instance of \\ArrayAccess, but is an instance of class Cscr\\SlimsApiBundle\\Entity\\SampleTypeTemplateAttribute. You can avoid this error by setting the \"data_class\" option to \"Cscr\\SlimsApiBundle\\Entity\\SampleTypeTemplateAttribute\" or by adding a view transformer that transforms an instance of class Cscr\\SlimsApiBundle\\Entity\\SampleTypeTemplateAttribute to scalar, array or an instance of \\ArrayAccess."}
```

Well, I think I doing something wrong. I will waiting for your comments before continue

**Comment by StuBez** [comment]
That sounds like a bug I've created. I'll fix it today.

**Comment by suzzopher** [comment]
Looks good.
