### ISSUE TITLE
Display document URL in sample search results

### ISSUE THREAD

**Issue by StuBez** [littlerobot/slims#57]
I am just adding the functionality to return the document URL in the sample search response.

I can think of two options and wondered which you thought would be better:
1. I add a `url` element to `instance_attributes` and `type_attributes` that are documents.
2. I set the `value` to the URL when the attribute type is `document`.

Example for 1:
```json
{
  "success": true,
  "results": [
    {
      "container": 11,
      "container_name": "Test [1]",
      "row": 0,
      "column": 0,
      "colour": "#FFFFFF",
      "type": 2,
      "type_name": "MEF",
      "instance_template": 2,
      "instance_template_name": "No dates",
      "instance_attributes": [
        {
          "id": 415,
          "label": "Test",
          "type": "document",
          "url": "/app_dev.php/download/sample-instance-attributes/415/mef%20tracking.xlsx"
        }
      ],
      "type_attributes": [
        {
          "id": 4,
          "label": "Media",
          "type": "brief-text",
          "value": "Dmem, 10% serum, 2ME"
        }
      ]
    }
  ]
}
```

@chuckn0rris What do you think? Do you have any other ideas?

**Comment by chuckn0rris** [comment]
@StuBez "type": "document" and "url" parameter - is perfect here. I will develop special renderer for each type of our attributes according to "type" value.

**Comment by StuBez** [comment]
That's how it should work now so please let me know if you have any problems with the data.

**Comment by chuckn0rris** [comment]
@StuBez I cannot get any search results - it's always empty.


name:
user:
stored_start:20/10/2012
passage_number:
container:
stored_end:20/10/2015

{"success":false}

**Comment by StuBez** [comment]
@chuckn0rris That is probably because the templates have to be set up in a special way for most of the searches to work. Try using the container name - that should work for all template types.

**Comment by chuckn0rris** [comment]
Request URL:http://slims.dev/app_dev.php/api/samples?_dc=1445664089107&name=&user=&stored_start=&passage_number=&container=Wedge&stored_end=

{"success":false}

<img width="763" alt="2015-10-24_1222" src="https://cloud.githubusercontent.com/assets/7203098/10709044/f4e494c8-7a49-11e5-8154-7166f61f294d.png">

**Comment by StuBez** [comment]
Have you got the latest code from GitHub? I added a fix for the search yesterday.

**Comment by chuckn0rris** [comment]
@StuBez no, I didn't.
Now I've updated the code and have new error

Request URL:http://slims.dev/app_dev.php/api/samples?_dc=1445688957241&name=&user=&stored_start=&passage_number=&container=Wed&stored_end=

{
  "code": 500,
  "message": "Unexpected data found., Unexpected data found., Trailing data"
}

I tried to remove _dc parameter but have the same problem.

**Comment by StuBez** [comment]
@chuckn0rris That might be because I had to change the way dates are stored to allow them to be searched. Can you try making a new container and store some new samples in that. I think searching for samples just in that new container will solve this problem. If that doesn't work I will try to think of something else.

**Comment by chuckn0rris** [comment]
@StuBez you was right. I've created a new container and samples inside and search is working for them. Thank you!

**Comment by suzzopher** [comment]
Looks good.
