### ISSUE TITLE
Defect: Unable to add new container when using 'Stored Inside'

### ISSUE THREAD

**Issue by suzzopher** [littlerobot/slims#58]
When attempting to add a new container selecting Stored Inside you are not able to due to a Server error.

See attached screenshot.
![screen shot 2015-09-08 at 20 58 27](https://cloud.githubusercontent.com/assets/173174/9745960/bfa5189c-566c-11e5-8e3c-0dd573a2c375.png)

**Comment by StuBez** [comment]
I think I fixed this bug in 4ddd68f but hadn't got round to deploying it yet. It's now deployed and I was able to add a child container.

**Comment by suzzopher** [comment]
Yep this is now working as expected.
