### ISSUE TITLE
Defect: Unable to use selector in number of containers to create selector

### ISSUE THREAD

**Issue by suzzopher** [littlerobot/slims#59]
When adding a new container if you try to increase/decrease in the number of containers to create selector nothing happens.

If this is not intended to be working functionality perhaps it would be best to remove it as to not confuse users.

**Comment by StuBez** [comment]
I agree that part of the dialog should be removed.

**Comment by suzzopher** [comment]
@StuBez @chuckn0rris This is still the same as before, has it been deployed?

**Comment by StuBez** [comment]
@suzzopher That's a very good question! I've just deployed the latest code now. Apologies if I'd missed it before.

**Comment by suzzopher** [comment]
Great stuff now fixed.
![screen shot 2015-09-29 at 20 43 18](https://cloud.githubusercontent.com/assets/173174/10176111/cba61022-66ea-11e5-8772-3d9c3f18951c.png)
