### ISSUE TITLE
Defect: Hitting back on the keyboard causes the user to be returned to the login screen

### ISSUE THREAD

**Issue by suzzopher** [littlerobot/slims#60]
When you are using the back button when the cursor is not in a text field it will cause the user to be taken to the login screen.

Additionally clicking forward in the browser will put you back and logged in.

**Comment by chuckn0rris** [comment]
This is standard behavior for any web page. What's wrong?

**Comment by suzzopher** [comment]
@chuckn0rris Sorry I missed a bit of information here. I should have said when you have a pop up window open. Which for me seems to be a bit jarring as a user.

**Comment by chuckn0rris** [comment]
@suzzopher In any case, this is standard browser behavior. Opened window - it is just a visual css effect.
I can investigate this situation, but this is not a bug or defect.
If you about close a window - please, use Esc button.

**Comment by StuBez** [comment]
We'll leave this issue for now and see if there is time to do anything later.
