### ISSUE TITLE
Defect: Samples | Cursor will cause the search fields to look empty in hover state and break the date picker

### ISSUE THREAD

**Issue by suzzopher** [littlerobot/slims#63]
When you are filling in the search fields with the cursor hovered over the field you are typing in it will look as though you are not typing anything. If you hover over each of the fields the text will be hidden. 

Edit: If you have a date selected and want to change you will not be able to as hovering over the date picker will make the date picker become hidden

Steps to reproduce:
* Go to Samples
* Click into the search field keep the cursor hovered there
* Start typing 
* Observe it will look as though you are not typing

* In completed fields 
* Hover the cursor
* Observe that the text will be hidden

**Comment by chuckn0rris** [comment]
http://screencast.com/t/xmcPgi2KY4
@suzzopher I cannot understand what you are talking about. Please, watch the video. Do you see a bug there?

**Comment by suzzopher** [comment]
@chuckn0rris That video didn't work for me, I have attached mine here
http://www.screencast.com/t/suj8vgtFbl

**Comment by chuckn0rris** [comment]
@suzzopher I can't reproduce. 
What browser did you used? OS? Can you try to reproduce it in another browser?

**Comment by chuckn0rris** [comment]
@suzzopher OK, I see this bug on http://slims.littlerobot.io/

**Comment by chuckn0rris** [comment]
@StuBez I see we use not index.html file in production version of our site, but dashboard.html.twig

I am generate web/build/production/index.html for that purpose, there all works fine. So, the problem is that I changed index.html and know nothing about dashboard.html.twig. I'll fix it now, and I think we should do nothing with this problem in the future, because I change index.html very very rarely.

**Comment by StuBez** [comment]
@chuckn0rris That makes sense. I think you said it was easier for you to use the `index.html` file when developing.

**Comment by suzzopher** [comment]
Excellent this is now working as expected.
