### ISSUE TITLE
Wording changes

### ISSUE THREAD

**Issue by suzzopher** [littlerobot/slims#64]
Little niggle but a UK based company would ideally want Oxford spellings see screenshot.
![screen shot 2015-09-08 at 21 40 03](https://cloud.githubusercontent.com/assets/173174/9746882/5f9c4afa-5672-11e5-99f9-6aa74618856b.png)

**Comment by StuBez** [comment]
@suzzopher Just thinking, it would probably make sense to list all the changes in one issues so they can all be changed in one go.

**Comment by suzzopher** [comment]
@StuBez Good idea, will focus on the wording during my session on Monday and update this issue appropriately.

**Comment by chuckn0rris** [comment]
Fixed `colour`
