### ISSUE TITLE
Defect: The drop down in the capacity area for Remaining and Total needs to be re-aligned

### ISSUE THREAD

**Issue by suzzopher** [littlerobot/slims#65]
When you click on the drop down for either Remaining or Total it will cut off the end of each word to open the drop down menu.

See screenshot.
![screen shot 2015-09-08 at 21 44 50](https://cloud.githubusercontent.com/assets/173174/9746973/dc4e42e2-5672-11e5-9aee-971a77cb3f47.png)

**Comment by StuBez** [comment]
Fixed as part of #86.
