### ISSUE TITLE
Send user requests as JSON

### ISSUE THREAD

**Issue by StuBez** [littlerobot/slims#67]
It looks like creating and editing users sends the request with a content type of `application/x-www-form-urlencoded`. Please change this so that it is sent as JSON.

Example:
```json
{
    "username": "test2",
    "name": "Test",
    "research_group": null,
    "is_active": false
}
```

Also,
- `research_group` should be `null` if none is selected in the UI.
- `is_active` should be `true` if checked or `false` otherwise.

**Comment by chuckn0rris** [comment]
@StuBez 
Request:
`{"username":"newuser02","name":"New USer Name","research_group":null,"is_active":false}`
Response:
```
{
  "code": 400,
  "message": "Validation Failed",
  "errors": {
    "errors": [
      "Is active status must be set."
    ],
    "children": {
      "name": [
        
      ],
      "username": [
        
      ],
      "research_group": [
        
      ],
      "is_active": [
        
      ]
    }
  }
}
```

**Comment by StuBez** [comment]
@chuckn0rris Thanks. The validation needed slightly changing.

**Comment by suzzopher** [comment]
Cool all good.
