### ISSUE TITLE
Improvement: Should there be some indication of edit/delete field in attributes?

### ISSUE THREAD

**Issue by suzzopher** [littlerobot/slims#69]
In the Instance Template all columns are named but the one with edit/delete is blank in the column but doesn't say what the column is.
![screen shot 2015-09-12 at 16 38 27](https://cloud.githubusercontent.com/assets/173174/9832253/25dea9fe-596d-11e5-8bd7-15b4b9366a9f.png)

This is also a column in groups and users.
![screen shot 2015-09-12 at 16 48 22](https://cloud.githubusercontent.com/assets/173174/9832294/1b064c66-596e-11e5-9a7b-36f47fe9f111.png)

Above is the containers page and again nothing to note what these columns are, as a user could be confusing.

**Comment by chuckn0rris** [comment]
@suzzopher This is ok for Ext JS UI. All this buttons have tooltips with information. Also we haven't a text there because it will takes more space (I am about width for these columns), as this happens with Capacity columns - simple number takes more space than it needed because it has long title.

**Comment by StuBez** [comment]
I think users will understand the icons but we can rethink this if they have problems.
