### ISSUE TITLE
Users can create single containers via the UI

### ISSUE THREAD

**Issue by StuBez** [littlerobot/slims#7]
Create user interface and API endpoints to allow the creation of new containers.

## Fields
* Name
  * Text
  * 255 characters
* Parent (_stored inside_ field)
  * ID of another container that has a _stores_ value of _containers_
  * `null` if it just stores other containers
* Owner (_belongs to_ field)
  * `null` OR a research group ID
* Dimensions
  * integers
* Stores
  * Either _samples_ or _other containers_
* Colour
  * Hexadecimal, e.g. #ff00ff
* Comment
  * Long text
* Number of containers to create
  * Set to _1_ until #16 is complete

## API format
`/api/containers [POST]`
```
{
	"name": "...",
	"parent": null,
	"parent": 1,
	"research_group": null,
	"research_group": 15,
	"rows": 10,
	"columns": 10,
	"stores": "containers",
	"stores": "samples",
	"comment": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.",
	"colour": null,
	"colour": "#00dd21"
}
```
> `stores` can be `samples` or `containers`.
> `parent`, `research_group`, `comment`, and `colour` can be set to `null`.

## Mockup
![new container](https://cloud.githubusercontent.com/assets/910068/4875669/24da0282-62a2-11e4-8b14-ea380a9fca77.png)

The mockup is just a suggestion and can be modified to fit in with ExtJS.

**Comment by chuckn0rris** [comment]
I finished

**Comment by StuBez** [comment]
Looks good. :+1: I'll get feedback from the client.
