### ISSUE TITLE
Allow sample type to have no attributes

### ISSUE THREAD

**Issue by StuBez** [littlerobot/slims#70]
After discussion with users, not all samples will have attributes that are common for all of them. It is useful to have a template and type so that we can display the names in the table, though.

- [x] Update API to return "Types" with no attributes.
- [x] Update search results to only display "Type attributes" columns if there are any values in the API response.

The screenshot shows what happens if you select a "Type" with no attributes.

<img width="1440" alt="screen shot 2015-09-16 at 11 09 15" src="https://cloud.githubusercontent.com/assets/910068/9902072/9cc85792-5c63-11e5-9b30-9cb67ee23bfd.png">

**Comment by StuBez** [comment]
@suzzopher Could you check if this is now working correctly. You'll need to add (or find!) a sample with an attribute that is blank.

**Comment by suzzopher** [comment]
Yep looks good.
