### ISSUE TITLE
Change search options

### ISSUE THREAD

**Issue by StuBez** [littlerobot/slims#72]
The users would like to change one of the search options.

- [x] Update API to use `passage_number`, instead of `type`.
- [x] Update Javascript to use `passage_number`, instead of `type` in request.
- [x] Change minimum number of characters in UI to 1, rather than 3. Dates should be validated as they are already.
- [x] Change label from "Sample Type" to "Passage number".

**Comment by StuBez** [comment]
I have updated the API to match the new format.

The new URL is `GET /api/samples?name=xxx&user=yyy&stored_start=zzz&stored_end=aaa&passage_number=bbb&container=ccc`.

**Comment by StuBez** [comment]
#73 means that the date search does not return the correct results but that doesn't matter for what you are working on.

**Comment by StuBez** [comment]
@suzzopher I've had a quick check and it looks like the search criteria is working as expected. I would be grateful if you could check as well, though.

**Comment by suzzopher** [comment]
Search looks to be working.
