### ISSUE TITLE
Search for samples in date range returns invalid results

### ISSUE THREAD

**Issue by StuBez** [littlerobot/slims#73]
I assume because the field is just text, rather than a date, doing a `BETWEEN` in MySQL isn't working correctly.

**Comment by StuBez** [comment]
This only fixes dates that are set after the fix goes live. I haven't added a fix for existing data because the system isn't being used by end-users yet.

**Comment by suzzopher** [comment]
@StuBez I am not getting any search results back

**Comment by StuBez** [comment]
@suzzopher It's probable that only the "Container name" field will work in the test environment as the other fields rely on the instance attribute labels being called specific things:
- Sample/cell line name
- Passage number
- User Name
- Date frozen

You could test this by creating a new instance template which has those named fields, though.

**Comment by StuBez** [comment]
It also relies on #72 being completed as there was a client-requested change in the fields that should be searched.

**Comment by suzzopher** [comment]
@StuBez Still not able to get anything back in the search.

**Comment by StuBez** [comment]
@suzzopher I created a new instance template (Search test) and was able to search by all the search field types. The only issue I could see is that the client asked for "sample type" to be changed to "passage number", which means the field that is currently being searched is wrong.

<img width="1433" alt="screen shot 2015-09-30 at 09 01 38" src="https://cloud.githubusercontent.com/assets/910068/10187670/e6f72048-6751-11e5-8338-ac36c0ef64b0.png">

If it's still not working for you, can you make sure you're using the "Search test" instance template. If that doesn't fix it, a video of what you're seeing happen will hopefully allow me to see what's not working.

**Comment by suzzopher** [comment]
Yep all looking good now.
