### ISSUE TITLE
Improvement: When creating a new attribute in instance template the new option text should be removed

### ISSUE THREAD

**Issue by suzzopher** [littlerobot/slims#75]
when the user starts typing, at the moment you have to manually delete which is a bit of a pain.

Steps to reproduce:
* Go to Samples > Instance Template 
* Select template
* Add attribute option
* Then add new option
* Observe that the New Option text has to be deleted manually to enter your own text

**Comment by chuckn0rris** [comment]
Removed default text, fixed validation.
