### ISSUE TITLE
Unable to edit Types after opening one type to edit

### ISSUE THREAD

**Issue by suzzopher** [littlerobot/slims#76]
When you try to edit the types, once you open a type to edit even if you don't save the edit you will not be able to edit another type unless you refresh the page.

Steps to reproduce:
- Go to Samples > Types
- Click edit pencil
- Once the edit window opens
- either save or close it
- Now click the pencil for any other type
- Observe that you cannot
- Refresh the page and repeat the above

**Comment by chuckn0rris** [comment]
@suzzopher can't reproduce.
http://screencast.com/t/MzCynYhJXee

**Comment by StuBez** [comment]
@suzzopher Could you try to make a video showing this issue?
