### ISSUE TITLE
Adding new container has formatting issues in IE11

### ISSUE THREAD

**Issue by suzzopher** [littlerobot/slims#78]
When you are trying to add a new container on IE11 you will see there are formatting issues. See attached screen shot.

![2015-10-11_2013](https://cloud.githubusercontent.com/assets/173174/10418535/96500698-7055-11e5-8beb-6217ebcde5e0.png)

**Comment by chuckn0rris** [comment]
@StuBez Can you check it in IE11? I have only Mac today.

**Comment by suzzopher** [comment]
@StuBez Are you not wanting this fixed? It is still an issue and I thought the customer would primarily being using IE.

**Comment by StuBez** [comment]
@suzzopher I closed the issue so that it appeared in the list of things for you to test - I thought we'd been closing issues we had fixed and you using that to see what needing re-testing.

**Comment by StuBez** [comment]
@suzzopher Sorry, mis-read your comment. I think we'll make the IE11 issues part of a future phase as I'm not aware of anyone who uses it.
