### ISSUE TITLE
Server error returned when you first log in and access Users tab

### ISSUE THREAD

**Issue by suzzopher** [littlerobot/slims#81]
See attached video.

This is seen in IE11, Chrome and Firefox for Windows.

C:\Users\Laptop\Desktop\2015-10-27_1952.swf

**Comment by StuBez** [comment]
@suzzopher Could you try uploading the video again, please - the link doesn't seem to have worked. I'll see if I can reproduce it in the meantime as it's quite likely something to do with the backend code.

**Comment by StuBez** [comment]
This was caused by the import of live data that I performed last week. The research groups were reset but the users were left so there were users with no matching group, causing it to blow up. I've fixed the data so it should be OK again.

**Comment by suzzopher** [comment]
Yep no longer seeing this.
