### ISSUE TITLE
Editing Container | When belongs to a group is selected you can change it in edit container 

### ISSUE THREAD

**Issue by suzzopher** [littlerobot/slims#84]
When belongs to a group is selected you can change it in edit container after even if it is greyed out.

Steps to reproduce:
* Create a new container
* Select Belongs to and choose a group
* Save 
* Now click on the edit pencil next to your new container
* Go to the group drop down and select a group
* Select Save 
* Observe it looks as though it has saved but it hasn't

Expected result:
If this is greyed out it should not be possible for the drop down box to open

**Comment by suzzopher** [comment]
![2015-10-31_2056](https://cloud.githubusercontent.com/assets/173174/10865864/ad6bd4a2-8012-11e5-8c8c-b4c0ed23caad.png)

**Comment by StuBez** [comment]
Superseded by #91.
