### ISSUE TITLE
Users can edit existing containers via the UI

### ISSUE THREAD

**Issue by StuBez** [littlerobot/slims#9]
Allow certain container properties to be modified after the container was initially created.

As a first implementation, only allow updates to the following fields. The specification of these fields is in #7
* Name
* Colour
* Comment

## API format
`/api/containers/{id} [POST]`
```
{
	"name": "...",
	"comment": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.",
	"colour": "#00dd21"
}
```
> `comment`, and `colour` can be set to `null`.

## UI design
I don't have any UI designs in mind for this. There is already some code in the _Container demo_ tab in https://github.com/littlerobot/slims/tree/feature/9-edit-containers.

**Comment by chuckn0rris** [comment]
I just disable fields which user cannot change http://screencast.com/t/C1DlNC16c
Ready
